/******************************************************************************
** Copyright (c) 2013-2023 Intel Corporation All Rights Reserved
**
** Licensed under the Apache License, Version 2.0 (the "License"); you may not
** use this file except in compliance with the License.
**
** You may obtain a copy of the License at
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
** WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
**
** See the License for the specific language governing permissions and
** limitations under the License.
**
******************************************************************************/

#include "esif_ccb.h"
#include "esif_ccb_string.h"
#include "esif_sdk_primitive_type.h"
#include "esif_sdk_event_type.h"
#include "esif_sdk_event_guid.h"
#include "esif_sdk_event_map.h"
#include "esif_sdk_iface.h"
#include "esif_sdk_guid.h"

#include "ipf_ipc_codec.h"
#include "ipfsrv_appmgr.h"
#include "ipfsrv_authmgr.h"
#include "ipf_trace.h"

/////////////////////////////////////////////////////////////////////////////////
// IPF Server Authentication Manager (Access Control)
// Authentication is enforced by the OS using OS-Specific Security ACLs
// that are bound to an Authorization Role and a Server Listener Address that
// supports OS Security ACLs (such as Unix Domain Sockets or Windows Named Pipes)
// NOTE: The number of Server Addresses cannot exceed IPF_WS_MAX_LISTENERS
/////////////////////////////////////////////////////////////////////////////////

// Authentication Manager Singleton Instance
static AccessDef g_AccessMgr[] = {

#ifdef ESIF_ATTR_DEBUG
		{ "ws://127.0.0.1:18086",	IPFAUTH_ROLE_PUBLIC,	NULL },			// Public Access over Localhost TCP/IP port 18086
		{ "ws://0.0.0.0:18088",		IPFAUTH_ROLE_ROOT,		NULL },			// All Access over Local/Remote TCP/IP port 18088
#endif

#ifdef ESIF_ATTR_DEBUG
		{ "pipe://ipfsrv.public",	IPFAUTH_ROLE_PUBLIC,	"rw-rw-rw-:root:root" },	// Public Access over Local Logical Pipe (All users)
		{ "pipe://ipfsrv.elevated",	IPFAUTH_ROLE_ELEVATED,	"rw-rw----:root:root" },	// Elevated Access over Local Logical Pipe (root only)
#endif
		{ "pipe://ipfsrv.dptf",		IPFAUTH_ROLE_DPTF,		"rw-rw----:daemon:daemon",	"Dptf.so",		{ .opt.DttAccessControl = 1 } },		// DPTF Manager Role
#ifdef ESIF_ATTR_DEBUG
		{ "pipe://ipfsrv.dptftcs",	IPFAUTH_ROLE_DPTFTCS,	"rw-rw----:daemon:daemon",	"dptftcs.so",	{ .opt.DttAccessControl = 1, .opt.TcsAccessControl = 1 } },	// DPTF Telemetry Role
#endif
		{ "pipe://ipfsrv.dptfui",	IPFAUTH_ROLE_DPTFUI,	"rw-rw----:daemon:daemon",	"ipf_ws.so",	{ .opt.GenericUIAccessControl = 1, .opt.DttAccessControl = 1 } },	// DPTF UI Role
#ifdef ESIF_ATTR_DEBUG
		{ "pipe://ipfsrv.ipfui",	IPFAUTH_ROLE_IPFUI,		"rw-rw----:daemon:daemon",	"ipfui.so",		{ .opt.GenericUIAccessControl = 1 } },	// IPF UI Role
		{ "pipe://ipfsrv.root",		IPFAUTH_ROLE_ROOT,		"rw-rw----:root:root" },	// All Access over Local Logical Pipe (root only)
#endif
		{ NULL }
};

// Authentication Manager
esif_error_t AccessMgr_Init(void);
void AccessMgr_Exit(void);

esif_error_t AccessMgr_Init(void)
{
	return ESIF_OK;
}

void AccessMgr_Exit(void)
{
}

const AccessDef *AccessMgr_GetAccessDefs(void)
{
	return g_AccessMgr;
}

//////////////////////////////////////////
//// Access Control List Definitions  ////
//// v1 is static; v2 will be dynamic ////
//////////////////////////////////////////

//// Access Control List Typedefs ////

// Get/Set Config ACLs
typedef struct AclConfig_s {
	Bool		permit;
	esif_string	nameSpace;
	esif_string	keyName;
} AclConfig;

// Execute Primitive ACLs
typedef struct AclPrimitive_s {
	Bool					permit;
	esif_primitive_type_t	primitiveId;
} AclPrimitive;

// WriteLog ACLs
typedef struct AclWriteLog_s {
	Bool		permit;
	eLogType	minLogType;
	eLogType	maxLogType;
} AclWriteLog;

// Register/Unregister/Send Event ACLs
typedef struct AclEvent_s {
	Bool		permit;
	esif_guid_t	guid;
} AclEvent;

// Send Command ACLs
typedef struct AclCommand_s {
	Bool		permit;
	esif_string	command;
} AclCommand;

// Combined Access Control List Definition
typedef struct AclAuthDef_s {
	char			name[ESIF_NAME_LEN];
	AclConfig		*EsifGetConfig;
	AclConfig		*EsifSetConfig;
	AclPrimitive	*EsifPrimitive;
	AclWriteLog		*EsifWriteLog;
	AclEvent		*EsifEventRegister;
	AclEvent		*EsifEventUnregister;
	AclEvent		*EsifSendEvent;
	AclCommand		*EsifSendCommand;
} AuthAclDef;

///////////////////////////////////////////////////////////////////////////////
// IPF Server Authorization Manager (Authorization Roles)
// Authorization is enforced using Authorization Roles that are bound with
// Authenticated Clients that connect to Server Listeners.
// Currently Implemented as ESIF Interface Function Set.
// esifHandle = Actual ESIF Handle, not IPF Client Session Handle
///////////////////////////////////////////////////////////////////////////////

// Authorization Manager
typedef struct AuthMgr_s {
	AuthAclDef	roles[IPFAUTH_MAX_ROLES];		// Number of supported Roles
} AuthMgr;

// Authentication Manager Singleton Instance
AuthMgr g_AuthMgr;

#define ACL_PERMIT	ESIF_TRUE	// Permit Access
#define ACL_DENY	ESIF_FALSE	// Deny Access

#define	IPF_AUTH_DEFAULT	ACL_DENY	// Deny All by Default
#define IPF_ACL_HASDATA(a)	(a && memcmp(&a[j], &nullAuth, sizeof(nullAuth)) != 0)

// Convert a Role Handle into an Role Table Index
#define IPFAUTH_ROLE_INDEX(role)	((role >= IPFAUTH_ROLE_NONE && role < IPFAUTH_ROLE_NONE + ESIF_ARRAY_LEN(g_AuthMgr.roles)) ? (role - IPFAUTH_ROLE_NONE) : 0)

// Return Combined Access Control List Definition for specified Authentication Handle
static ESIF_INLINE AuthAclDef AuthMgr_GetAuthAclDef(esif_handle_t authHandle)
{
	AuthAclDef authDef = { 0 };

	switch (authHandle) {

	// ROOT Role = All Access
	case IPFAUTH_ROLE_ROOT:
	{
		// Authorized ESIF Interface Parameters for ROOT Role
		static AclConfig root_GetConfig[] = {
			{ ACL_PERMIT },	// Permit All
			{ 0 },
		};
		static AclConfig root_SetConfig[] = {
			{ ACL_PERMIT },	// Permit All
			{ 0 },
		};
		static AclPrimitive root_Primitive[] = {
			{ ACL_PERMIT },	// Permit All
			{ 0 },
		};
		static AclWriteLog root_WriteLog[] = {
			{ ACL_PERMIT }, // Permit All
			{ 0 },
		};
		static AclEvent root_Event[] = {
			{ ACL_PERMIT },	// Permit All
			{ 0 },
		};
		static AclEvent root_EventSend[] = {
			{ ACL_PERMIT },	// Permit All
			{ 0 },
		};
		static AclCommand root_Command[] = {
			{ ACL_PERMIT },	// Permit All
			{ 0 },
		};
		AuthAclDef rootAuth = {
			.name = "root",
			.EsifGetConfig = root_GetConfig,
			.EsifSetConfig = root_SetConfig,
			.EsifPrimitive = root_Primitive,
			.EsifWriteLog = root_WriteLog,
			.EsifEventRegister = root_Event,
			.EsifEventUnregister = root_Event,
			.EsifSendEvent = root_EventSend,
			.EsifSendCommand = root_Command,
		};
		authDef = rootAuth;
		break;
	}

	// PUBLIC Role = Read-Only + Limited Primitives, Events, and Commands
	case IPFAUTH_ROLE_PUBLIC:
	{
		// Authorized ESIF Interface Parameters for PUBLIC Role
		static AclConfig public_GetConfig[] = {
			{ 0 },	// Deny All
		};
		static AclConfig public_SetConfig[] = {
			{ 0 },	// Deny All
		};
		static AclPrimitive public_Primitive[] = {
			{ ACL_PERMIT,	GET_ACUR },
			{ ACL_PERMIT,	GET_ADAPTER_POWER_RATING },
			{ ACL_PERMIT,	GET_AGGREGATE_DISPLAY_INFORMATION },
			{ ACL_PERMIT,	GET_AP01 },
			{ ACL_PERMIT,	GET_AP02 },
			{ ACL_PERMIT,	GET_AP10 },
			{ ACL_PERMIT,	GET_AVOL },
			{ ACL_PERMIT,	GET_BATTERY_HIGH_FREQUENCY_IMPEDANCE },
			{ ACL_PERMIT,	GET_BATTERY_MAX_PEAK_CURRENT },
			{ ACL_PERMIT,	GET_BATTERY_NO_LOAD_VOLTAGE },
			{ ACL_PERMIT,	GET_BATTERY_PERCENTAGE },
			{ ACL_PERMIT,	GET_CHARGER_TYPE },
			{ ACL_PERMIT,	GET_CPU_UTILIZATION },
			{ ACL_PERMIT,	GET_DEVICE_UNIQUE_ID },
			{ ACL_PERMIT,	GET_FAN_INFORMATION },
			{ ACL_PERMIT,	GET_FAN_PERFORMANCE_STATES },
			{ ACL_PERMIT,	GET_FAN_STATUS },
			{ ACL_PERMIT,	GET_HW_SOC_WORKLOAD },
			{ ACL_PERMIT,	GET_HWP_GUARANTEED_PERFORMANCE_LEVEL },
			{ ACL_PERMIT,	GET_HWP_HIGHEST_PERFORMANCE_LEVEL },
			{ ACL_PERMIT,	GET_HWP_LOWEST_PERFORMANCE_LEVEL },
			{ ACL_PERMIT,	GET_HWP_MOST_EFFICIENT_PERFORMANCE_LEVEL },
			{ ACL_PERMIT,	GET_PARTICIPANT_FRIENDLY_NAME },
			{ ACL_PERMIT,	GET_PARTICIPANT_TYPE },
			{ ACL_PERMIT,	GET_PERF_PREFERENCE_MAX },
			{ ACL_PERMIT,	GET_PERF_PREFERENCE_MIN },
			{ ACL_PERMIT,	GET_PERF_PSTATE_DEPTH_LIMIT },
			{ ACL_PERMIT,	GET_PLATFORM_BATTERY_STEADY_STATE },
			{ ACL_PERMIT,	GET_PLATFORM_MAX_BATTERY_POWER },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT_DUTY_CYCLE },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT_ENABLE },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_SOURCE },
			{ ACL_PERMIT,	GET_PLATFORM_REST_OF_POWER },
			{ ACL_PERMIT,	GET_PROC_LOGICAL_PROCESSOR_COUNT },
			{ ACL_PERMIT,	GET_PROC_THERMAL_DESIGN_POWER },
			{ ACL_PERMIT,	GET_PROC_TJMAX },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT_DUTY_CYCLE },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT_ENABLE },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	GET_RAPL_POWER_MAX },
			{ ACL_PERMIT,	GET_RAPL_POWER_MIN },
			{ ACL_PERMIT,	GET_SOC_WORKLOAD },
			{ ACL_PERMIT,	GET_SOC_DGPU_WEIGHTS },
			{ ACL_PERMIT,	GET_TCC_LOCK_STATUS },
			{ ACL_PERMIT,	GET_TCC_OFFSET },
			{ ACL_PERMIT,	GET_TEMPERATURE_THRESHOLDS },
			{ ACL_PERMIT,	GET_TEMPERATURE },
			{ 0 },
		};
		static AclWriteLog public_WriteLog[] = {
			{ ACL_PERMIT,	eLogTypeFatal,	eLogTypeDebug }, // Permit All
			{ 0 },
		};
		static AclEvent public_Event[] = {
			{ ACL_PERMIT,	APP_BROADCAST },
			{ ACL_PERMIT,	APP_BROADCAST_UNPRIVILEGED },
			{ ACL_PERMIT,	BIOMETRIC_PRESENCE_SENSOR_DISTANCE_CHANGED },
			{ ACL_PERMIT,	CHARGER_TYPE_CHANGED },
			{ ACL_PERMIT,	COLLABORATION_CHANGED },
			{ ACL_PERMIT,	DEVICE_ORIENTATION_CHANGED },
			{ ACL_PERMIT,	DISPLAY_ORIENTATION_CHANGED },
			{ ACL_PERMIT,	EXTERNAL_MONITOR_CONNECTION_STATE_CHANGED },
			{ ACL_PERMIT,	LOG_VERBOSITY_CHANGED },
			{ ACL_PERMIT,	MOTION_CHANGED },
			{ ACL_PERMIT,	OS_BATTERY_PERCENT_CHANGED },
			{ ACL_PERMIT,	OS_DOCK_MODE_CHANGED },
			{ ACL_PERMIT,	OS_GAME_MODE_CHANGED },
			{ ACL_PERMIT,	OS_LID_STATE_CHANGED },
			{ ACL_PERMIT,	OS_MIXED_REALITY_MODE_CHANGED },
			{ ACL_PERMIT,	OS_PLATFORM_TYPE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SLIDER_VALUE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SOURCE_CHANGED },
			{ ACL_PERMIT,	OS_POWERSCHEME_PERSONALITY_CHANGED },
			{ ACL_PERMIT,	OS_SCREEN_STATE_CHANGED },
			{ ACL_PERMIT,	OS_USER_INTERACTION_CHANGED },
			{ ACL_PERMIT,	OS_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	PLATFORM_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	SENSOR_MODE_CHANGED },
			{ ACL_PERMIT,	SENSOR_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	SYSTEM_IN_BAG },
			{ ACL_PERMIT,	TEMP_THRESHOLD_CROSSED },
			{ ACL_PERMIT,	WINDOWS_LOW_POWER_MODE_ENTRY },
			{ ACL_PERMIT,	WINDOWS_LOW_POWER_MODE_EXIT },
			{ ACL_PERMIT,	WORKLOAD_CLASSIFICATION_CHANGED },
			{ 0 },
		};
		static AclEvent public_EventSend[] = {
			{ ACL_PERMIT,	APP_BROADCAST_UNPRIVILEGED },
			{ 0 },
		};
		static AclCommand public_Command[] = {
			{ 0 },
		};
		AuthAclDef publicAuth = {
			.name = "public",
			.EsifGetConfig = public_GetConfig,
			.EsifSetConfig = public_SetConfig,
			.EsifPrimitive = public_Primitive,
			.EsifWriteLog = public_WriteLog,
			.EsifEventRegister = public_Event,
			.EsifEventUnregister = public_Event,
			.EsifSendEvent = public_EventSend,
			.EsifSendCommand = public_Command,
		};
		authDef = publicAuth;
		break;
	}

	// ELEVATED Role = Read-Only + Limited SET Primitives, Events, and Commands
	case IPFAUTH_ROLE_ELEVATED:
	{
		// Authorized ESIF Interface Parameters for ELEVATED Role
		static AclConfig elevated_GetConfig[] = {
			{ 0 },	// Deny All
		};
		static AclConfig elevated_SetConfig[] = {
			{ 0 },	// Deny All
		};
		static AclPrimitive elevated_Primitive[] = {
			{ ACL_PERMIT,	GET_ACUR },
			{ ACL_PERMIT,	GET_ADAPTER_POWER_RATING },
			{ ACL_PERMIT,	GET_AGGREGATE_DISPLAY_INFORMATION },
			{ ACL_PERMIT,	GET_AP01 },
			{ ACL_PERMIT,	GET_AP02 },
			{ ACL_PERMIT,	GET_AP10 },
			{ ACL_PERMIT,	GET_AVOL },
			{ ACL_PERMIT,	GET_BATTERY_HIGH_FREQUENCY_IMPEDANCE },
			{ ACL_PERMIT,	GET_BATTERY_MAX_PEAK_CURRENT },
			{ ACL_PERMIT,	GET_BATTERY_NO_LOAD_VOLTAGE },
			{ ACL_PERMIT,	GET_BATTERY_PERCENTAGE },
			{ ACL_PERMIT,	GET_CHARGER_TYPE },
			{ ACL_PERMIT,	GET_CPU_UTILIZATION },
			{ ACL_PERMIT,	GET_DEVICE_UNIQUE_ID },
			{ ACL_PERMIT,	GET_FAN_INFORMATION },
			{ ACL_PERMIT,	GET_FAN_PERFORMANCE_STATES },
			{ ACL_PERMIT,	GET_FAN_STATUS },
			{ ACL_PERMIT,	GET_HW_SOC_WORKLOAD },
			{ ACL_PERMIT,	GET_HWP_GUARANTEED_PERFORMANCE_LEVEL },
			{ ACL_PERMIT,	GET_HWP_HIGHEST_PERFORMANCE_LEVEL },
			{ ACL_PERMIT,	GET_HWP_LOWEST_PERFORMANCE_LEVEL },
			{ ACL_PERMIT,	GET_HWP_MOST_EFFICIENT_PERFORMANCE_LEVEL },
			{ ACL_PERMIT,	GET_IA_CLIP_REASONS },
			{ ACL_PERMIT,	GET_PARTICIPANT_FRIENDLY_NAME },
			{ ACL_PERMIT,	GET_PARTICIPANT_PERF_PRESENT_CAPABILITY },
			{ ACL_PERMIT,	GET_PARTICIPANT_TYPE },
			{ ACL_PERMIT,	GET_PERF_PREFERENCE_MAX },
			{ ACL_PERMIT,	GET_PERF_PREFERENCE_MIN },
			{ ACL_PERMIT,	GET_PERF_PSTATE_DEPTH_LIMIT },
			{ ACL_PERMIT,	GET_PLATFORM_BATTERY_STEADY_STATE },
			{ ACL_PERMIT,	GET_PLATFORM_MAX_BATTERY_POWER },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT_DUTY_CYCLE },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT_ENABLE },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_SOURCE },
			{ ACL_PERMIT,	GET_PLATFORM_REST_OF_POWER },
			{ ACL_PERMIT,	GET_PROC_LOGICAL_PROCESSOR_COUNT },
			{ ACL_PERMIT,	GET_PROC_THERMAL_DESIGN_POWER },
			{ ACL_PERMIT,	GET_PROC_TJMAX },
			{ ACL_PERMIT,	GET_RAPL_ENERGY },
			{ ACL_PERMIT,	GET_RAPL_POWER },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT_DUTY_CYCLE },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT_ENABLE },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	GET_RAPL_POWER_MAX },
			{ ACL_PERMIT,	GET_RAPL_POWER_MIN },
			{ ACL_PERMIT,	GET_SOC_WORKLOAD },
			{ ACL_PERMIT,	GET_SOC_DGPU_WEIGHTS },
			{ ACL_PERMIT,	GET_TCC_LOCK_STATUS },
			{ ACL_PERMIT,	GET_TCC_OFFSET },
			{ ACL_PERMIT,	GET_TEMPERATURE },
			{ ACL_PERMIT,	GET_TEMPERATURE_THRESHOLDS },
			{ ACL_PERMIT,	SET_FAN_LEVEL },
			{ ACL_PERMIT,	SET_PERF_PREFERENCE_MAX },
			{ ACL_PERMIT,	SET_PERF_PREFERENCE_MIN },
			{ ACL_PERMIT,	SET_PLATFORM_POWER_LIMIT },
			{ ACL_PERMIT,	SET_PLATFORM_POWER_LIMIT_DUTY_CYCLE },
			{ ACL_PERMIT,	SET_PLATFORM_POWER_LIMIT_ENABLE },
			{ ACL_PERMIT,	SET_PLATFORM_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	SET_PROC_NUMBER_OFFLINE_CORES },
			{ ACL_PERMIT,	SET_RAPL_POWER_LIMIT },
			{ ACL_PERMIT,	SET_RAPL_POWER_LIMIT_DUTY_CYCLE },
			{ ACL_PERMIT,	SET_RAPL_POWER_LIMIT_ENABLE },
			{ ACL_PERMIT,	SET_RAPL_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	SET_TCC_OFFSET },
			{ ACL_PERMIT,	SET_TEMPERATURE_THRESHOLDS },
			{ 0 },
		};
		static AclWriteLog elevated_WriteLog[] = {
			{ ACL_PERMIT,	eLogTypeFatal,	eLogTypeDebug }, // Permit All
			{ 0 },
		};
		static AclEvent elevated_Event[] = {
			{ ACL_PERMIT,	APP_BROADCAST },
			{ ACL_PERMIT,	APP_BROADCAST_UNPRIVILEGED },
			{ ACL_PERMIT,	BIOMETRIC_PRESENCE_SENSOR_DISTANCE_CHANGED },
			{ ACL_PERMIT,	CHARGER_TYPE_CHANGED },
			{ ACL_PERMIT,	COLLABORATION_CHANGED },
			{ ACL_PERMIT,	DEVICE_ORIENTATION_CHANGED },
			{ ACL_PERMIT,	DISPLAY_ORIENTATION_CHANGED },
			{ ACL_PERMIT,	EXTERNAL_MONITOR_CONNECTION_STATE_CHANGED },
			{ ACL_PERMIT,	LOG_VERBOSITY_CHANGED },
			{ ACL_PERMIT,	MOTION_CHANGED },
			{ ACL_PERMIT,	OS_BATTERY_PERCENT_CHANGED },
			{ ACL_PERMIT,	OS_DOCK_MODE_CHANGED },
			{ ACL_PERMIT,	OS_GAME_MODE_CHANGED },
			{ ACL_PERMIT,	OS_LID_STATE_CHANGED },
			{ ACL_PERMIT,	OS_MIXED_REALITY_MODE_CHANGED },
			{ ACL_PERMIT,	OS_PLATFORM_TYPE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SLIDER_VALUE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SOURCE_CHANGED },
			{ ACL_PERMIT,	OS_POWERSCHEME_PERSONALITY_CHANGED },
			{ ACL_PERMIT,	OS_SCREEN_STATE_CHANGED },
			{ ACL_PERMIT,	OS_USER_INTERACTION_CHANGED },
			{ ACL_PERMIT,	OS_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	PLATFORM_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	SENSOR_MODE_CHANGED },
			{ ACL_PERMIT,	SENSOR_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	SYSTEM_IN_BAG },
			{ ACL_PERMIT,	TEMP_THRESHOLD_CROSSED },
			{ ACL_PERMIT,	WINDOWS_LOW_POWER_MODE_ENTRY },
			{ ACL_PERMIT,	WINDOWS_LOW_POWER_MODE_EXIT },
			{ ACL_PERMIT,	WORKLOAD_CLASSIFICATION_CHANGED },
			{ 0 },
		};
		static AclEvent elevated_EventSend[] = {
			{ ACL_PERMIT,	APP_BROADCAST },
			{ ACL_PERMIT,	APP_BROADCAST_UNPRIVILEGED },
			{ ACL_PERMIT,	SENSOR_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	BIOMETRIC_PRESENCE_SENSOR_INSTANCE_CHANGED },
			{ 0 },
		};
		static AclCommand elevated_Command[] = {
			{ 0 },
		};
		AuthAclDef elevatedAuth = {
			.name = "elevated",
			.EsifGetConfig = elevated_GetConfig,
			.EsifSetConfig = elevated_SetConfig,
			.EsifPrimitive = elevated_Primitive,
			.EsifWriteLog = elevated_WriteLog,
			.EsifEventRegister = elevated_Event,
			.EsifEventUnregister = elevated_Event,
			.EsifSendEvent = elevated_EventSend,
			.EsifSendCommand = elevated_Command,
		};
		authDef = elevatedAuth;
		break;
	}

	// DTPF Role = Dynamic Tuning Technology Manager
	case IPFAUTH_ROLE_DPTF:
	{
		// Authorized ESIF Interface Parameters for DPTF Role
		static AclConfig dptf_GetConfig[] = {
			{ ACL_PERMIT,	"dptf" },
			{ ACL_PERMIT,	"override" },
			{ ACL_PERMIT,	"ppm" },
			{ 0 },
		};
		static AclConfig dptf_SetConfig[] = {
			{ ACL_PERMIT,	"dptf" },
			{ ACL_PERMIT,	"override" },
			{ 0 },
		};
		static AclPrimitive dptf_Primitive[] = {
			{ ACL_PERMIT,	GET_AC_PEAK_POWER },
			{ ACL_PERMIT,	GET_ACTIVE_CONTROL_POINT_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	GET_ACTIVE_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	GET_ACTIVITY_COUNTER_WIDTH },
			{ ACL_PERMIT,	GET_ACUR },
			{ ACL_PERMIT,	GET_ADAPTER_POWER_RATING },
			{ ACL_PERMIT,	GET_AGGREGATE_DISPLAY_INFORMATION },
			{ ACL_PERMIT,	GET_AGGRESSIVENESS_LEVEL },
			{ ACL_PERMIT,	GET_AP01 },
			{ ACL_PERMIT,	GET_AP02 },
			{ ACL_PERMIT,	GET_AP10 },
			{ ACL_PERMIT,	GET_AVOL },
			{ ACL_PERMIT,	GET_BASELINE_SSC_GUARD_BAND },
			{ ACL_PERMIT,	GET_BASELINE_SSC_SPREAD_VALUE },
			{ ACL_PERMIT,	GET_BASELINE_SSC_THRESHOLD },
			{ ACL_PERMIT,	GET_BATTERY_HIGH_FREQUENCY_IMPEDANCE },
			{ ACL_PERMIT,	GET_BATTERY_INFORMATION },
			{ ACL_PERMIT,	GET_BATTERY_MAX_PEAK_CURRENT },
			{ ACL_PERMIT,	GET_BATTERY_NO_LOAD_VOLTAGE },
			{ ACL_PERMIT,	GET_BATTERY_PERCENTAGE },
			{ ACL_PERMIT,	GET_BATTERY_STATUS },
			{ ACL_PERMIT,	GET_CHARGER_TYPE },
			{ ACL_PERMIT,	GET_CONFIG_ACCESS_CONTROL_SUR },
			{ ACL_PERMIT,	GET_CONFIG_TDP_CONTROL },
			{ ACL_PERMIT,	GET_CONFIG_TDP_LEVEL0 },
			{ ACL_PERMIT,	GET_CONFIG_TDP_LEVEL1 },
			{ ACL_PERMIT,	GET_CONFIG_TDP_LEVEL2 },
			{ ACL_PERMIT,	GET_CONFIG_TDP_LOCK },
			{ ACL_PERMIT,	GET_CORE_ACTIVITY_COUNTER },
			{ ACL_PERMIT,	GET_CPU_RWEIGHT },
			{ ACL_PERMIT,	GET_DC_PEAK_POWER },
			{ ACL_PERMIT,	GET_DDR_DVFS_DATA_RATE },
			{ ACL_PERMIT,	GET_DDR_RFI_TABLE },
			{ ACL_PERMIT,	GET_DISENGAGED_STABILITY_WINDOW },
			{ ACL_PERMIT,	GET_DISPLAY_BRIGHTNESS },
			{ ACL_PERMIT,	GET_DISPLAY_BRIGHTNESS_LEVELS },
			{ ACL_PERMIT,	GET_DISPLAY_BRIGHTNESS_SOFT },
			{ ACL_PERMIT,	GET_DISPLAY_CAPABILITY },
			{ ACL_PERMIT,	GET_DISPLAY_DEPTH_LIMIT },
			{ ACL_PERMIT,	GET_DLVR_REVISION },
			{ ACL_PERMIT,	GET_DLVR_PLL_FREQ_CHANGE_BUSY },
			{ ACL_PERMIT,	GET_DLVR_RFI_ENABLE },
			{ ACL_PERMIT,	GET_DOMAIN_PRIORITY },
			{ ACL_PERMIT,	GET_DYNAMIC_BOOST_STATE },
			{ ACL_PERMIT,	GET_EMERGENCY_CALL_MODE_TABLE },
			{ ACL_PERMIT,	GET_EPP_SENSITIVITY_HINT_MODEL },
			{ ACL_PERMIT,	GET_ES_DISPLAY_REQUIRED },
			{ ACL_PERMIT,	GET_EXPECTED_BATTERY_LIFE },
			{ ACL_PERMIT,	GET_FAN_CAPABILITIES },
			{ ACL_PERMIT,	GET_FAN_INFORMATION },
			{ ACL_PERMIT,	GET_FAN_MODE_CAPABILITIES },
			{ ACL_PERMIT,	GET_FAN_OPERATING_MODE },
			{ ACL_PERMIT,	GET_FAN_PERFORMANCE_STATES },
			{ ACL_PERMIT,	GET_FAN_SPEED_HIGH_THRESHOLD },
			{ ACL_PERMIT,	GET_FAN_SPEED_LOW_THRESHOLD },
			{ ACL_PERMIT,	GET_FAN_SPEED_THRESHOLD_HYSTERESIS },
			{ ACL_PERMIT,	GET_FAN_STATUS },
			{ ACL_PERMIT,	GET_FAST_POLL_TIME },
			{ ACL_PERMIT,	GET_GT_RWEIGHT },
			{ ACL_PERMIT,	GET_HW_SOC_WORKLOAD },
			{ ACL_PERMIT,	GET_HWP_EPP_VALUE },
			{ ACL_PERMIT,	GET_HWPF_STATE },
			{ ACL_PERMIT,	GET_INSTANTANEOUS_POWER },
			{ ACL_PERMIT,	GET_INTELLIGENT_THERMAL_MANAGEMENT_TABLE },
			{ ACL_PERMIT,	GET_IP_ALIGNMENT_SETTINGS },
			{ ACL_PERMIT,	GET_IPU_RWEIGHT },
			{ ACL_PERMIT,	GET_LAST_EWMA_POWER },
			{ ACL_PERMIT,	GET_LAST_POWER_USED },
			{ ACL_PERMIT,	GET_MINIMUM_SAMPLE_PERIOD },
			{ ACL_PERMIT,	GET_MEDIA_RWEIGHT },
			{ ACL_PERMIT,	GET_NEGATIVE_EVENT_FILTERING_STATE },
			{ ACL_PERMIT,	GET_NOT_PRESENT_STABILITY_WINDOW },
			{ ACL_PERMIT,	GET_NOTIFICATION_TEMP_THRESHOLD },
			{ ACL_PERMIT,	GET_OEM_VARS },
			{ ACL_PERMIT,	GET_OPTIMIZATION_SLIDER },
			{ ACL_PERMIT,	GET_OPTIMIZATION_SLIDER_STATUS },
			{ ACL_PERMIT,	GET_PARTICIPANT_CAPABILITIES },
			{ ACL_PERMIT,	GET_PARTICIPANT_ENERGY_THRESHOLD },
			{ ACL_PERMIT,	GET_PARTICIPANT_FRIENDLY_NAME },
			{ ACL_PERMIT,	GET_PARTICIPANT_HANDLE_LIST },
			{ ACL_PERMIT,	GET_PARTICIPANT_MAX_CORE_UTILIZATION },
			{ ACL_PERMIT,	GET_PARTICIPANT_PERF_PRESENT_CAPABILITY },
			{ ACL_PERMIT,	GET_PARTICIPANT_RESIDENCY_UTILIZATION },
			{ ACL_PERMIT,	GET_PARTICIPANT_UTILIZATION },
			{ ACL_PERMIT,	GET_PARTICIPANT_UTILIZATION_THRESHOLD },
			{ ACL_PERMIT,	GET_PASSIVE_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	GET_PCIE_THROTTLING_OPTION },
			{ ACL_PERMIT,	GET_PERF_PREFERENCE_MAX },
			{ ACL_PERMIT,	GET_PERF_PREFERENCE_MIN },
			{ ACL_PERMIT,	GET_PERF_PSTATE_DEPTH_LIMIT },
			{ ACL_PERMIT,	GET_PERF_SUPPORT_STATES },
			{ ACL_PERMIT,	GET_PID_ALGORITHM_TABLE },
			{ ACL_PERMIT,	GET_PID_KI_TERM },
			{ ACL_PERMIT,	GET_PID_KP_TERM },
			{ ACL_PERMIT,	GET_PID_TIME_AVERAGE_CONSTANT },
			{ ACL_PERMIT,	GET_PLATFORM_BATTERY_STEADY_STATE },
			{ ACL_PERMIT,	GET_PLATFORM_MAX_BATTERY_POWER },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT_DUTY_CYCLE },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT_ENABLE },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_SOURCE },
			{ ACL_PERMIT,	GET_PLATFORM_REST_OF_POWER },
			{ ACL_PERMIT,	GET_POSITIVE_EVENT_FILTERING_STATE },
			{ ACL_PERMIT,	GET_POWER_ALPHA },
			{ ACL_PERMIT,	GET_POWER_BOSS_ACTIONS_TABLE },
			{ ACL_PERMIT,	GET_POWER_BOSS_CONDITIONS_TABLE },
			{ ACL_PERMIT,	GET_POWER_BOSS_MATH_TABLE },
			{ ACL_PERMIT,	GET_POWER_DELTA },
			{ ACL_PERMIT,	GET_POWER_SEED },
			{ ACL_PERMIT,	GET_POWER_SHARE_TEMPERATURE_THRESHOLD },
			{ ACL_PERMIT,	GET_POWER_SHARING_ALGORITHM_TABLE },
			{ ACL_PERMIT,	GET_POWER_SHARING_ALGORITHM_TABLE_2 },
			{ ACL_PERMIT,	GET_POWERSHARE_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	GET_PPM_PARAM_VALUES },
			{ ACL_PERMIT,	GET_PRESENT_STABILITY_WINDOW },
			{ ACL_PERMIT,	GET_PROC_LOGICAL_PROCESSOR_COUNT },
			{ ACL_PERMIT,	GET_PROC_PERF_PRESENT_CAPABILITY },
			{ ACL_PERMIT,	GET_PROC_PERF_PSTATE_DEPTH_LIMIT },
			{ ACL_PERMIT,	GET_PROC_PERF_SUPPORT_STATES },
			{ ACL_PERMIT,	GET_PROC_PERF_THROTTLE_PRESENT_CAPABILITY },
			{ ACL_PERMIT,	GET_PROC_PERF_TSTATE_DEPTH_LIMIT },
			{ ACL_PERMIT,	GET_PROC_PHYSICAL_CORE_COUNT },
			{ ACL_PERMIT,	GET_PROC_THERMAL_DESIGN_POWER },
			{ ACL_PERMIT,	GET_PROC_TJMAX },
			{ ACL_PERMIT,	GET_PROC_TSC },
			{ ACL_PERMIT,	GET_RAPL_ENERGY },
			{ ACL_PERMIT,	GET_RAPL_ENERGY_COUNTER_INFO },
			{ ACL_PERMIT,	GET_RAPL_ENERGY_COUNTER_INFO_SUR },
			{ ACL_PERMIT,	GET_RAPL_ENERGY_COUNTER_WIDTH },
			{ ACL_PERMIT,	GET_RAPL_ENERGY_UNIT },
			{ ACL_PERMIT,	GET_RAPL_ENERGY_UNIT_CPU_SUR },
			{ ACL_PERMIT,	GET_RAPL_ENERGY_UNIT_GPU_SUR },
			{ ACL_PERMIT,	GET_RAPL_FLOOR_STATE },
			{ ACL_PERMIT,	GET_RAPL_POWER },
			{ ACL_PERMIT,	GET_RAPL_POWER_CONTROL_CAPABILITIES },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT_DUTY_CYCLE },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT_ENABLE },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	GET_RAPL_POWER_MIN },
			{ ACL_PERMIT,	GET_RF_ACTIVE_CHANNELS },
			{ ACL_PERMIT,	GET_RF_CHANNEL_INFO },
			{ ACL_PERMIT,	GET_RFI_DISABLE },
			{ ACL_PERMIT,	GET_RFPROFILE_CENTER_FREQUENCY },
			{ ACL_PERMIT,	GET_RFPROFILE_CENTER_FREQUENCY_DLVR },
			{ ACL_PERMIT,	GET_RFPROFILE_DEFAULT_CENTER_FREQUENCY },
			{ ACL_PERMIT,	GET_RFPROFILE_FREQUENCY_ADJUST_RESOLUTION },
			{ ACL_PERMIT,	GET_RFPROFILE_MAX_FREQUENCY },
			{ ACL_PERMIT,	GET_RFPROFILE_MIN_FREQUENCY },
			{ ACL_PERMIT,	GET_RFPROFILE_SSC },
			{ ACL_PERMIT,	GET_RFPROFILE_SSC_DLVR },
			{ ACL_PERMIT,	GET_RFPROFILE_SSC_DLVR_CTRL_LOCK },
			{ ACL_PERMIT,	GET_RFPROFILE_WIFI24_FREQ_GUARD_BAND },
			{ ACL_PERMIT,	GET_RFPROFILE_WIFI5_FREQ_GUARD_BAND },
			{ ACL_PERMIT,	GET_RFPROFILE_WWAN_FREQ_GUARD_BAND },
			{ ACL_PERMIT,	GET_SLOW_POLL_TIME },
			{ ACL_PERMIT,	GET_SLOWPOLL_POWER_THRESHOLD },
			{ ACL_PERMIT,	GET_SOC_DGPU_WEIGHTS },
			{ ACL_PERMIT,	GET_SOC_POWER_FLOOR_STATE },
			{ ACL_PERMIT,	GET_SOC_WORKLOAD },
			{ ACL_PERMIT,	GET_SOCWLC_SOURCE },
			{ ACL_PERMIT,	GET_SUPPORT_EPP_HINT },
			{ ACL_PERMIT,	GET_SUPPORTED_POLICIES },
			{ ACL_PERMIT,	GET_TCC_OFFSET },
			{ ACL_PERMIT,	GET_TEMPERATURE },
			{ ACL_PERMIT,	GET_TEMPERATURE_THRESHOLD_HYSTERESIS },
			{ ACL_PERMIT,	GET_TEMPERATURE_THRESHOLDS },
			{ ACL_PERMIT,	GET_THERMAL_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	GET_TPG_POWER_STATE },
			{ ACL_PERMIT,	GET_TRIP_POINT_ACTIVE },
			{ ACL_PERMIT,	GET_TRIP_POINT_CRITICAL },
			{ ACL_PERMIT,	GET_TRIP_POINT_HOT },
			{ ACL_PERMIT,	GET_TRIP_POINT_PASSIVE },
			{ ACL_PERMIT,	GET_TRIP_POINT_WARM },
			{ ACL_PERMIT,	GET_TSC_WIDTH },
			{ ACL_PERMIT,	GET_TSTATES },
			{ ACL_PERMIT,	GET_VIRTUAL_SENSOR_CALIB_TABLE },
			{ ACL_PERMIT,	GET_VIRTUAL_SENSOR_POLLING_TABLE },
			{ ACL_PERMIT,	GET_VOLTAGE_THRESHOLD_MATH_TABLE },
			{ ACL_PERMIT,	GET_VPU_RWEIGHT },
			{ ACL_PERMIT,	GET_WEIGHTED_SLOWPOLL_CONSTANT },
			{ ACL_PERMIT,	GET_WIFI_CAPABILITIES },
			{ ACL_PERMIT,	SET_AC_PEAK_POWER },
			{ ACL_PERMIT,	SET_ACTIVE_CONTROL_POINT_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	SET_ACTIVE_POWER_SCHEME },
			{ ACL_PERMIT,	SET_ACTIVE_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	SET_APP_ALIVE_RESPONSE },
			{ ACL_PERMIT,	SET_APP_COMPAT },
			{ ACL_PERMIT,	SET_APP_COMPAT_DELETE },
			{ ACL_PERMIT,	SET_BATTERY_PERCENTAGE },
			{ ACL_PERMIT,	SET_CONFIG_RESET },
			{ ACL_PERMIT,	SET_CPU_RWEIGHT },
			{ ACL_PERMIT,	SET_DC_PEAK_POWER },
			{ ACL_PERMIT,	SET_DDR_DVFS_RFI_RESTRICTION },
			{ ACL_PERMIT,	SET_DDR_RFI_TABLE },
			{ ACL_PERMIT,	SET_DEVICE_TEMPERATURE_INDICATION },
			{ ACL_PERMIT,	SET_DISPLAY_BRIGHTNESS },
			{ ACL_PERMIT,	SET_DISPLAY_BRIGHTNESS_LEVELS },
			{ ACL_PERMIT,	SET_DISPLAY_CAPABILITY },
			{ ACL_PERMIT,	SET_DISPLAY_DEPTH_LIMIT },
			{ ACL_PERMIT,	SET_DTT_MASTER_TO_CNVI },
			{ ACL_PERMIT,	SET_DYNAMIC_BOOST_STATE },
			{ ACL_PERMIT,	SET_EMERGENCY_CALL_MODE_TABLE },
			{ ACL_PERMIT,	SET_ENERGY_THRESHOLD_COUNT },
			{ ACL_PERMIT,	SET_ENERGY_THRESHOLD_INT_DISABLE },
			{ ACL_PERMIT,	SET_FAN_CAPABILITIES },
			{ ACL_PERMIT,	SET_FAN_DIRECTION },
			{ ACL_PERMIT,	SET_FAN_LEVEL },
			{ ACL_PERMIT,	SET_FAN_OPERATING_MODE },
			{ ACL_PERMIT,	SET_FAN_SPEED_HIGH_THRESHOLD },
			{ ACL_PERMIT,	SET_FAN_SPEED_LOW_THRESHOLD },
			{ ACL_PERMIT,	SET_FOREGROUND_APP_RATIO_PERIOD },
			{ ACL_PERMIT,	SET_GT_RWEIGHT },
			{ ACL_PERMIT,	SET_INTELLIGENT_THERMAL_MANAGEMENT_TABLE },
			{ ACL_PERMIT,	SET_IP_ALIGNMENT_DISABLE },
			{ ACL_PERMIT,	SET_IP_ALIGNMENT_ENABLE },
			{ ACL_PERMIT,	SET_IP_ALIGNMENT_START },
			{ ACL_PERMIT,	SET_IP_ALIGNMENT_SUPPORT_STATE },
			{ ACL_PERMIT,	SET_IP_ALIGNMENT_STOP },
			{ ACL_PERMIT,	SET_IPU_RWEIGHT },
			{ ACL_PERMIT,	SET_LAST_EWMA_POWER },
			{ ACL_PERMIT,	SET_LAST_POWER_USED },
			{ ACL_PERMIT,	SET_MEDIA_RWEIGHT },
			{ ACL_PERMIT,	SET_OEM_VARS },
			{ ACL_PERMIT,	SET_OPERATING_SYSTEM_CAPABILITIES },
			{ ACL_PERMIT,	SET_OPTIMIZATION_SLIDER },
			{ ACL_PERMIT,	SET_OS_BATTERY_PERCENTAGE },
			{ ACL_PERMIT,	SET_OS_POWER_SOURCE },
			{ ACL_PERMIT,	SET_PARTICIPANT_ENERGY_THRESHOLD },
			{ ACL_PERMIT,	SET_PARTICIPANT_MAX_PERF_STATE },
			{ ACL_PERMIT,	SET_PARTICIPANT_RESIDENCY_UTILIZATION },
			{ ACL_PERMIT,	SET_PARTICIPANT_UTILIZATION_THRESHOLD },
			{ ACL_PERMIT,	SET_PASSIVE_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	SET_PBOK },
			{ ACL_PERMIT,	SET_PERF_PREFERENCE_MAX },
			{ ACL_PERMIT,	SET_PERF_PREFERENCE_MIN },
			{ ACL_PERMIT,	SET_PERF_PRESENT_CAPABILITY },
			{ ACL_PERMIT,	SET_PERF_PSTATE_DEPTH_LIMIT },
			{ ACL_PERMIT,	SET_PERF_SUPPORT_STATES },
			{ ACL_PERMIT,	SET_PID_ALGORITHM_TABLE },
			{ ACL_PERMIT,	SET_PID_KI_TERM },
			{ ACL_PERMIT,	SET_PID_KP_TERM },
			{ ACL_PERMIT,	SET_PID_TIME_AVERAGE_CONSTANT },
			{ ACL_PERMIT,	SET_PLATFORM_POWER_LIMIT },
			{ ACL_PERMIT,	SET_PLATFORM_POWER_LIMIT_DUTY_CYCLE },
			{ ACL_PERMIT,	SET_PLATFORM_POWER_LIMIT_ENABLE },
			{ ACL_PERMIT,	SET_PLATFORM_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	SET_POWER_BOSS_ACTIONS_TABLE },
			{ ACL_PERMIT,	SET_POWER_BOSS_CONDITIONS_TABLE },
			{ ACL_PERMIT,	SET_POWER_BOSS_MATH_TABLE },
			{ ACL_PERMIT,	SET_POWER_SCHEME_EPP },
			{ ACL_PERMIT,	SET_POWER_SHARE_EFFECTIVE_BIAS },
			{ ACL_PERMIT,	SET_POWER_SHARE_POLICY_POWER },
			{ ACL_PERMIT,	SET_POWER_SHARE_TEMPERATURE_THRESHOLD },
			{ ACL_PERMIT,	SET_POWER_SHARING_ALGORITHM_TABLE },
			{ ACL_PERMIT,	SET_POWER_SHARING_ALGORITHM_TABLE_2 },
			{ ACL_PERMIT,	SET_PPM_NON_BALANCED_VALUES },
			{ ACL_PERMIT,	SET_PPM_PARAM_VALUES },
			{ ACL_PERMIT,	SET_PPM_PARAMS_TO_NULL },
			{ ACL_PERMIT,	SET_PROC_MAX_THROTTLE_STATE },
			{ ACL_PERMIT,	SET_PROC_NUMBER_OFFLINE_CORES },
			{ ACL_PERMIT,	SET_PROC_PERF_PSTATE_DEPTH_LIMIT },
			{ ACL_PERMIT,	SET_PROC_PERF_SUPPORT_STATES },
			{ ACL_PERMIT,	SET_PROC_PERF_TSTATE_DEPTH_LIMIT },
			{ ACL_PERMIT,	SET_PROCESS_AFFINITY_MASK },
			{ ACL_PERMIT,	SET_RAPL_FLOOR_STATE },
			{ ACL_PERMIT,	SET_RAPL_POWER_CONTROL_CAPABILITIES },
			{ ACL_PERMIT,	SET_RAPL_POWER_LIMIT },
			{ ACL_PERMIT,	SET_RAPL_POWER_LIMIT_CLEAR },
			{ ACL_PERMIT,	SET_RAPL_POWER_LIMIT_DUTY_CYCLE },
			{ ACL_PERMIT,	SET_RAPL_POWER_LIMIT_ENABLE },
			{ ACL_PERMIT,	SET_RAPL_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	SET_RAPL_POWER_MIN },
			{ ACL_PERMIT,	SET_RAPL_POWER_MIN_CLEAR },
			{ ACL_PERMIT,	SET_RF_ACTIVE_CHANNELS },
			{ ACL_PERMIT,	SET_RF_CHANNEL_INFO },
			{ ACL_PERMIT,	SET_RFPROFILE_CENTER_FREQUENCY },
			{ ACL_PERMIT,	SET_RFPROFILE_CENTER_FREQUENCY_DLVR },
			{ ACL_PERMIT,	SET_RFPROFILE_CENTER_FREQUENCY_DLVR_SUR },
			{ ACL_PERMIT,	SET_RFPROFILE_SSC_DLVR },
			{ ACL_PERMIT,	SET_RFPROFILE_SSC_DLVR_SUR },
			{ ACL_PERMIT,	SET_SLOWPOLL_POWER_THRESHOLD },
			{ ACL_PERMIT,	SET_SOCWC_DC_POLLING_PERIOD },
			{ ACL_PERMIT,	SET_SOCWC_SLOW_POLLING_PERIOD },
			{ ACL_PERMIT,	SET_SOCWLC_SOURCE },
			{ ACL_PERMIT,	SET_SUPPORT_EPP_HINT },
			{ ACL_PERMIT,	SET_SYSTEM_HIBERNATE },
			{ ACL_PERMIT,	SET_SYSTEM_SHUTDOWN },
			{ ACL_PERMIT,	SET_SYSTEM_SLEEP },
			{ ACL_PERMIT,	SET_TCC_OFFSET },
			{ ACL_PERMIT,	SET_TEMPERATURE_THRESHOLDS },
			{ ACL_PERMIT,	SET_THERMAL_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	SET_TRIP_POINT_ACTIVE },
			{ ACL_PERMIT,	SET_TRIP_POINT_PASSIVE },
			{ ACL_PERMIT,	SET_TSTATE_CURRENT },
			{ ACL_PERMIT,	SET_UNDER_VOLTAGE_THRESHOLD },
			{ ACL_PERMIT,	SET_VIRTUAL_SENSOR_CALIB_TABLE },
			{ ACL_PERMIT,	SET_VIRTUAL_TEMPERATURE },
			{ ACL_PERMIT,	SET_VOLTAGE_THRESHOLD_MATH_TABLE },
			{ ACL_PERMIT,	SET_VPU_RWEIGHT },
			{ ACL_PERMIT,	SET_WEIGHTED_SLOWPOLL_CONSTANT },
			{ 0 },
		};
		static AclWriteLog dptf_WriteLog[] = {
			{ ACL_PERMIT }, // Permit All
			{ 0 },
		};
		static AclEvent dptf_Event[] = {
			{ ACL_PERMIT,	APP_BROADCAST },
			{ ACL_PERMIT,	APP_BROADCAST_UNPRIVILEGED },
			{ ACL_PERMIT,	APP_UNLOADING },
			{ ACL_PERMIT,	BATTERY_COUNT_NOTIFICATION },
			{ ACL_PERMIT,	BATTERY_HIGH_FREQUENCY_IMPEDANCE_CHANGED },
			{ ACL_PERMIT,	BATTERY_INFORMATION_CHANGED },
			{ ACL_PERMIT,	BATTERY_NO_LOAD_VOLTAGE_CHANGED },
			{ ACL_PERMIT,	BATTERY_STATUS_CHANGED },
			{ ACL_PERMIT,	CHARGER_TYPE_CHANGED },
			{ ACL_PERMIT,	COLLABORATION_CHANGED },
			{ ACL_PERMIT,	CORE_CAPABILITY_CHANGED },
			{ ACL_PERMIT,	DEVICE_ORIENTATION_CHANGED },
			{ ACL_PERMIT,	DISPLAY_OFF },
			{ ACL_PERMIT,	DISPLAY_ON },
			{ ACL_PERMIT,	DISPLAY_ORIENTATION_CHANGED },
			{ ACL_PERMIT,	DTT_ACTIVE_CONTROL_POINT_RELATIONSHIP_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_ACTIVE_RELATIONSHIP_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_ALIVE_REQUEST },
			{ ACL_PERMIT,	DTT_DISPLAY_CAPABILITY_CHANGED },
			{ ACL_PERMIT,	DTT_DISPLAY_STATUS_CHANGED },
			{ ACL_PERMIT,	DTT_EPP_SENSITIVITY_HINT_CHANGED },
			{ ACL_PERMIT,	DTT_INTELLIGENT_THERMAL_MANAGEMENT_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_PARTICIPANT_ACTIVITY_LOGGING_DISABLED },
			{ ACL_PERMIT,	DTT_PARTICIPANT_ACTIVITY_LOGGING_ENABLED },
			{ ACL_PERMIT,	DTT_PASSIVE_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_PID_ALGORITHM_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_POLICY_ACTIVITY_LOGGING_DISABLED },
			{ ACL_PERMIT,	DTT_POLICY_ACTIVITY_LOGGING_ENABLED },
			{ ACL_PERMIT,	DTT_POWER_BOSS_ACTIONS_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_POWER_BOSS_CONDITIONS_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_POWER_BOSS_MATH_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_POWER_SHARING_ALGORITHM_TABLE_2_CHANGED },
			{ ACL_PERMIT,	DTT_POWER_SHARING_ALGORITHM_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_PRIORITY_CHANGED },
			{ ACL_PERMIT,	DTT_SUPPORTED_POLICIES_CHANGED },
			{ ACL_PERMIT,	DTT_SYSTEM_COOLING_POLICY_CHANGED },
			{ ACL_PERMIT,	DTT_THERMAL_RELATIONSHIP_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_VIRTUAL_SENSOR_CALIB_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_VIRTUAL_SENSOR_POLLING_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_VIRTUAL_SENSOR_RECALC_CHANGED },
			{ ACL_PERMIT,	DTT_VOLTAGE_THRESHOLD_MATH_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_WORKLOAD_HINT_CONFIGURATION_CHANGED },
			{ ACL_PERMIT,	EMERGENCY_CALL_MODE_TABLE_CHANGED },
			{ ACL_PERMIT,	ENERGY_THRESHOLD_CROSSED },
			{ ACL_PERMIT,	EXTERNAL_MONITOR_CONNECTION_STATE_CHANGED },
			{ ACL_PERMIT,	FAN_CAPABILITIES_CHANGED },
			{ ACL_PERMIT,	FAN_SPEED_THRESHOLD_CROSSED },
			{ ACL_PERMIT,	FOREGROUND_APP_CHANGED },
			{ ACL_PERMIT,	FOREGROUND_BACKGROUND_RATIO_CHANGED },
			{ ACL_PERMIT,	IP_ALIGNMENT_STATE_CHANGED },
			{ ACL_PERMIT,	LOG_VERBOSITY_CHANGED },
			{ ACL_PERMIT,	MAX_BATTERY_POWER_CHANGED },
			{ ACL_PERMIT,	MOTION_CHANGED },
			{ ACL_PERMIT,	OEM_VARS_CHANGED },
			{ ACL_PERMIT,	OS_BATTERY_PERCENT_CHANGED },
			{ ACL_PERMIT,	OS_DOCK_MODE_CHANGED },
			{ ACL_PERMIT,	OS_GAME_MODE_CHANGED },
			{ ACL_PERMIT,	OS_LID_STATE_CHANGED },
			{ ACL_PERMIT,	OS_MIXED_REALITY_MODE_CHANGED },
			{ ACL_PERMIT,	OS_MOBILE_NOTIFICATION },
			{ ACL_PERMIT,	OS_PLATFORM_TYPE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SLIDER_VALUE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SOURCE_CHANGED },
			{ ACL_PERMIT,	OS_POWERSCHEME_PERSONALITY_CHANGED },
			{ ACL_PERMIT,	OS_SCREEN_STATE_CHANGED },
			{ ACL_PERMIT,	OS_USER_INTERACTION_CHANGED },
			{ ACL_PERMIT,	OS_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	PARTICIPANT_RESUME },
			{ ACL_PERMIT,	PARTICIPANT_SPEC_INFO_CHANGED },
			{ ACL_PERMIT,	PARTICIPANT_SUSPEND },
			{ ACL_PERMIT,	PCIE_THROTTLE_REQUESTED },
			{ ACL_PERMIT,	PERF_CAPABILITY_CHANGED },
			{ ACL_PERMIT,	PERF_CONTROL_CHANGED },
			{ ACL_PERMIT,	PLATFORM_BATTERY_STEADY_STATE_CHANGED },
			{ ACL_PERMIT,	PLATFORM_POWER_SOURCE_CHANGED },
			{ ACL_PERMIT,	PLATFORM_REST_OF_POWER_CHANGED },
			{ ACL_PERMIT,	PLATFORM_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	POWER_CAPABILITY_CHANGED },
			{ ACL_PERMIT,	PROCESS_LOAD_NOTIFICATION },
			{ ACL_PERMIT,	RF_CONNECTION_STATUS_CHANGED },
			{ ACL_PERMIT,	RF_PROFILE_CHANGED },
			{ ACL_PERMIT,	SESSION_STATE_CHANGED },
			{ ACL_PERMIT,	SOC_POWER_FLOOR_CHANGED },
			{ ACL_PERMIT,	SOC_WORKLOADTYPE_CHANGED },
			{ ACL_PERMIT,	SYSTEM_IN_BAG },
			{ ACL_PERMIT,	TEMP_THRESHOLD_CROSSED },
			{ ACL_PERMIT,	TPG_POWER_STATE_CHANGED },
			{ ACL_PERMIT,	TPG_TPP_LIMIT_CHANGED },
			{ ACL_PERMIT,	WINDOWS_LOW_POWER_MODE_ENTRY },
			{ ACL_PERMIT,	WINDOWS_LOW_POWER_MODE_EXIT },
			{ ACL_PERMIT,	WORKLOAD_CLASSIFICATION_CHANGED },
			{ 0 },
		};
		static AclEvent dptf_EventSend[] = {
			{ ACL_PERMIT,	APP_BROADCAST },
			{ ACL_PERMIT,	APP_LOADED },
			{ ACL_PERMIT,	APP_UNLOADED },
			{ ACL_PERMIT,	DTT_PARTICIPANT_CONTROL_ACTION },
			{ ACL_PERMIT,	DTT_POLICY_LOADED_UNLOADED },
			{ ACL_PERMIT,	PARTICIPANT_CREATE },
			{ ACL_PERMIT,	PARTICIPANT_UNREGISTER },
			{ 0 },
		};
		static AclCommand dptf_Command[] = {
			{ 0 },
		};
		AuthAclDef dptfAuth = {
			.name = "dptf",
			.EsifGetConfig = dptf_GetConfig,
			.EsifSetConfig = dptf_SetConfig,
			.EsifPrimitive = dptf_Primitive,
			.EsifWriteLog = dptf_WriteLog,
			.EsifEventRegister = dptf_Event,
			.EsifEventUnregister = dptf_Event,
			.EsifSendEvent = dptf_EventSend,
			.EsifSendCommand = dptf_Command,
		};
		authDef = dptfAuth;
		break;
	}

	// DTPFTCS Role = Dynamic Tuning Technology Telemetry Collection Service
	case IPFAUTH_ROLE_DPTFTCS:
	{
		// Authorized ESIF Interface Parameters for DPTFTCS Role
		static AclConfig dptftcs_GetConfig[] = {
			{ ACL_PERMIT,	"dptf" },
			{ 0 },
		};
		static AclConfig dptftcs_SetConfig[] = {
			{ 0 },
		};
		static AclPrimitive dptftcs_Primitive[] = {
			{ ACL_PERMIT,	GET_ACTIVE_CONTROL_POINT_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	GET_ACTIVE_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	GET_ADAPTER_POWER_RATING },
			{ ACL_PERMIT,	GET_ADAPTIVE_PERFORMANCE_ACTIONS_TABLE },
			{ ACL_PERMIT,	GET_ADAPTIVE_PERFORMANCE_CONDITIONS_TABLE },
			{ ACL_PERMIT,	GET_CONFIG_ACCESS_CONTROL_SUR },
			{ ACL_PERMIT,	GET_CONFIG_TDP_CONTROL },
			{ ACL_PERMIT,	GET_CONFIG_TDP_LEVEL0 },
			{ ACL_PERMIT,	GET_CONFIG_TDP_LEVEL1 },
			{ ACL_PERMIT,	GET_CONFIG_TDP_LEVEL2 },
			{ ACL_PERMIT,	GET_CONFIG_TDP_LOCK },
			{ ACL_PERMIT,	GET_DISPLAY_BRIGHTNESS },
			{ ACL_PERMIT,	GET_EMERGENCY_CALL_MODE_TABLE },
			{ ACL_PERMIT,	GET_EPP_BATTERY_LIFE_BURSTY_THRESHOLD },
			{ ACL_PERMIT,	GET_FAN_MODE_CAPABILITIES },
			{ ACL_PERMIT,	GET_FAN_OPERATING_MODE },
			{ ACL_PERMIT,	GET_FAN_PERFORMANCE_STATES },
			{ ACL_PERMIT,	GET_IA_CLIP_REASONS },
			{ ACL_PERMIT,	GET_LAST_EWMA_POWER },
			{ ACL_PERMIT,	GET_MBT_MODEL_VERSION },
			{ ACL_PERMIT,	GET_OEM_VARS },
			{ ACL_PERMIT,	GET_PARTICIPANT_SAMPLE_PERIOD },
			{ ACL_PERMIT,	GET_PASSIVE_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	GET_PERF_SUPPORT_STATES },
			{ ACL_PERMIT,	GET_PID_ALGORITHM_TABLE },
			{ ACL_PERMIT,	GET_PLATFORM_POWER_LIMIT },
			{ ACL_PERMIT,	GET_PLATFORM_REST_OF_POWER },
			{ ACL_PERMIT,	GET_POWER_BOSS_ACTIONS_TABLE },
			{ ACL_PERMIT,	GET_POWER_BOSS_CONDITIONS_TABLE },
			{ ACL_PERMIT,	GET_POWER_BOSS_MATH_TABLE },
			{ ACL_PERMIT,	GET_POWER_SAMPLE_PERIOD },
			{ ACL_PERMIT,	GET_POWER_SHARING_ALGORITHM_TABLE },
			{ ACL_PERMIT,	GET_POWER_SHARING_ALGORITHM_TABLE_2 },
			{ ACL_PERMIT,	GET_PROC_PKG_CSTATE_RESIDENCY },
			{ ACL_PERMIT,	GET_PROC_THERMAL_DESIGN_POWER },
			{ ACL_PERMIT,	GET_PROC_TSC },
			{ ACL_PERMIT,	GET_RAPL_ENERGY },
			{ ACL_PERMIT,	GET_RAPL_ENERGY_UNIT },
			{ ACL_PERMIT,	GET_RAPL_POWER },
			{ ACL_PERMIT,	GET_RAPL_POWER_CONTROL_CAPABILITIES },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT },
			{ ACL_PERMIT,	GET_RAPL_POWER_LIMIT_TIME_WINDOW },
			{ ACL_PERMIT,	GET_SOCWC_POWER_DIFFS_COUNT_THRESHOLD },
			{ ACL_PERMIT,	GET_SUPPORTED_POLICIES },
			{ ACL_PERMIT,	GET_TEMPERATURE },
			{ ACL_PERMIT,	GET_THERMAL_RELATIONSHIP_TABLE },
			{ ACL_PERMIT,	GET_TRIP_POINT_ACTIVE },
			{ ACL_PERMIT,	GET_TRIP_POINT_CRITICAL },
			{ ACL_PERMIT,	GET_TRIP_POINT_HOT },
			{ ACL_PERMIT,	GET_TRIP_POINT_PASSIVE },
			{ ACL_PERMIT,	GET_TRIP_POINT_WARM },
			{ ACL_PERMIT,	GET_VIRTUAL_SENSOR_CALIB_TABLE },
			{ ACL_PERMIT,	GET_VIRTUAL_SENSOR_POLLING_TABLE },
			{ ACL_PERMIT,	GET_VOLTAGE_THRESHOLD_MATH_TABLE },
			{ 0 },
		};
		static AclWriteLog dptftcs_WriteLog[] = {
			{ ACL_PERMIT }, // Permit All
			{ 0 },
		};
		static AclEvent dptftcs_Event[] = {
			{ ACL_PERMIT,	APP_UNLOADING },
			{ ACL_PERMIT,	BATTERY_COUNT_NOTIFICATION },
			{ ACL_PERMIT,	BATTERY_HIGH_FREQUENCY_IMPEDANCE_CHANGED },
			{ ACL_PERMIT,	BATTERY_INFORMATION_CHANGED },
			{ ACL_PERMIT,	BATTERY_NO_LOAD_VOLTAGE_CHANGED },
			{ ACL_PERMIT,	BATTERY_STATUS_CHANGED },
			{ ACL_PERMIT,	CHARGER_TYPE_CHANGED },
			{ ACL_PERMIT,	CORE_CAPABILITY_CHANGED },
			{ ACL_PERMIT,	DEVICE_ORIENTATION_CHANGED },
			{ ACL_PERMIT,	DISPLAY_OFF },
			{ ACL_PERMIT,	DISPLAY_ON },
			{ ACL_PERMIT,	DISPLAY_ORIENTATION_CHANGED },
			{ ACL_PERMIT,	DTT_ACTIVE_CONTROL_POINT_RELATIONSHIP_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_ACTIVE_RELATIONSHIP_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_ADAPTIVE_PERFORMANCE_ACTIONS_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_ADAPTIVE_PERFORMANCE_CONDITIONS_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_ADAPTIVE_PERFORMANCE_PARTICIPANT_CONDITION_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_ALIVE_REQUEST },
			{ ACL_PERMIT,	DTT_DISPLAY_CAPABILITY_CHANGED },
			{ ACL_PERMIT,	DTT_DISPLAY_STATUS_CHANGED },
			{ ACL_PERMIT,	DTT_EPP_SENSITIVITY_HINT_CHANGED },
			{ ACL_PERMIT,	DTT_PARTICIPANT_ACTIVITY_LOGGING_DISABLED },
			{ ACL_PERMIT,	DTT_PARTICIPANT_ACTIVITY_LOGGING_ENABLED },
			{ ACL_PERMIT,	DTT_PASSIVE_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_PID_ALGORITHM_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_POLICY_ACTIVITY_LOGGING_DISABLED },
			{ ACL_PERMIT,	DTT_POLICY_ACTIVITY_LOGGING_ENABLED },
			{ ACL_PERMIT,	DTT_POWER_BOSS_ACTIONS_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_POWER_BOSS_CONDITIONS_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_POWER_BOSS_MATH_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_POWER_SHARING_ALGORITHM_TABLE_2_CHANGED },
			{ ACL_PERMIT,	DTT_POWER_SHARING_ALGORITHM_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_PRIORITY_CHANGED },
			{ ACL_PERMIT,	DTT_SUPPORTED_POLICIES_CHANGED },
			{ ACL_PERMIT,	DTT_SYSTEM_COOLING_POLICY_CHANGED },
			{ ACL_PERMIT,	DTT_THERMAL_RELATIONSHIP_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_VIRTUAL_SENSOR_CALIB_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_VIRTUAL_SENSOR_POLLING_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_VIRTUAL_SENSOR_RECALC_CHANGED },
			{ ACL_PERMIT,	DTT_VOLTAGE_THRESHOLD_MATH_TABLE_CHANGED },
			{ ACL_PERMIT,	DTT_WORKLOAD_HINT_CONFIGURATION_CHANGED },
			{ ACL_PERMIT,	EMERGENCY_CALL_MODE_TABLE_CHANGED },
			{ ACL_PERMIT,	ENERGY_THRESHOLD_CROSSED },
			{ ACL_PERMIT,	EXTERNAL_MONITOR_CONNECTION_STATE_CHANGED },
			{ ACL_PERMIT,	FAN_CAPABILITIES_CHANGED },
			{ ACL_PERMIT,	FOREGROUND_APP_CHANGED },
			{ ACL_PERMIT,	LOG_VERBOSITY_CHANGED },
			{ ACL_PERMIT,	MAX_BATTERY_POWER_CHANGED },
			{ ACL_PERMIT,	MOTION_CHANGED },
			{ ACL_PERMIT,	OEM_VARS_CHANGED },
			{ ACL_PERMIT,	OS_BATTERY_PERCENT_CHANGED },
			{ ACL_PERMIT,	OS_DOCK_MODE_CHANGED },
			{ ACL_PERMIT,	OS_GAME_MODE_CHANGED },
			{ ACL_PERMIT,	OS_LID_STATE_CHANGED },
			{ ACL_PERMIT,	OS_MIXED_REALITY_MODE_CHANGED },
			{ ACL_PERMIT,	OS_MOBILE_NOTIFICATION },
			{ ACL_PERMIT,	OS_PLATFORM_TYPE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SLIDER_VALUE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SOURCE_CHANGED },
			{ ACL_PERMIT,	OS_POWERSCHEME_PERSONALITY_CHANGED },
			{ ACL_PERMIT,	OS_SCREEN_STATE_CHANGED },
			{ ACL_PERMIT,	OS_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	PARTICIPANT_RESUME },
			{ ACL_PERMIT,	PARTICIPANT_SPEC_INFO_CHANGED },
			{ ACL_PERMIT,	PARTICIPANT_SUSPEND },
			{ ACL_PERMIT,	PERF_CAPABILITY_CHANGED },
			{ ACL_PERMIT,	PERF_CONTROL_CHANGED },
			{ ACL_PERMIT,	PLATFORM_BATTERY_STEADY_STATE_CHANGED },
			{ ACL_PERMIT,	PLATFORM_POWER_SOURCE_CHANGED },
			{ ACL_PERMIT,	PLATFORM_REST_OF_POWER_CHANGED },
			{ ACL_PERMIT,	PLATFORM_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	POWER_CAPABILITY_CHANGED },
			{ ACL_PERMIT,	RF_CONNECTION_STATUS_CHANGED },
			{ ACL_PERMIT,	RF_PROFILE_CHANGED },
			{ ACL_PERMIT,	SENSOR_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	SESSION_STATE_CHANGED },
			{ ACL_PERMIT,	TEMP_THRESHOLD_CROSSED },
			{ ACL_PERMIT,	WORKLOAD_CLASSIFICATION_CHANGED },
			{ 0 },
		};
		static AclEvent dptftcs_EventSend[] = {
			{ 0 },
		};
		static AclCommand dptftcs_Command[] = {
			{ ACL_PERMIT,	"apps" },
			{ 0 },
		};
		AuthAclDef dptftcsAuth = {
			.name = "dptftcs",
			.EsifGetConfig = dptftcs_GetConfig,
			.EsifSetConfig = dptftcs_SetConfig,
			.EsifPrimitive = dptftcs_Primitive,
			.EsifWriteLog = dptftcs_WriteLog,
			.EsifEventRegister = dptftcs_Event,
			.EsifEventUnregister = dptftcs_Event,
			.EsifSendEvent = dptftcs_EventSend,
			.EsifSendCommand = dptftcs_Command,
		};
		authDef = dptftcsAuth;
		break;
	}

	// DPTFUI Role = Dynamic Tuning Technology UI
	case IPFAUTH_ROLE_DPTFUI:
	{
		// Authorized ESIF Interface Parameters for DPTF_UI Role
		static AclConfig dptfui_GetConfig[] = {
			{ 0 },	// Deny All
		};
		static AclConfig dptfui_SetConfig[] = {
			{ 0 },	// Deny All
		};
		static AclPrimitive dptfui_Primitive[] = {
			{ 0 },	// Deny All
		};
		static AclWriteLog dptfui_WriteLog[] = {
			{ ACL_PERMIT }, // Permit All
			{ 0 },
		};
		static AclEvent dptfui_Event[] = {
			{ ACL_PERMIT,	LOG_VERBOSITY_CHANGED },
			{ 0 },
		};
		static AclEvent dptfui_EventSend[] = {
			{ 0 },
		};
		static AclCommand dptfui_Command[] = {
			{ ACL_PERMIT,	"about" },
			{ ACL_PERMIT,	"actionstart" },
			{ ACL_PERMIT,	"apps" },
			{ ACL_PERMIT,	"capture" },
			{ ACL_PERMIT,	"config" },
			{ ACL_PERMIT,	"devices" },
			{ ACL_PERMIT,	"dptf" },
			{ ACL_PERMIT,	"echo" },
			{ ACL_PERMIT,	"format" },
			{ ACL_PERMIT,	"getp" },
			{ ACL_PERMIT,	"getp_part" },
			{ ACL_PERMIT,	"idsp" },
			{ ACL_PERMIT,	"log" },
			{ ACL_PERMIT,	"participant" },
			{ ACL_PERMIT,	"participantlog" },
			{ ACL_PERMIT,	"participants" },
			{ ACL_PERMIT,	"rstp" },
			{ ACL_PERMIT,	"rstp_part" },
			{ ACL_PERMIT,	"setp" },
			{ ACL_PERMIT,	"setp_part" },
			{ ACL_PERMIT,	"status" },
			{ ACL_PERMIT,	"tableobject" },
			{ ACL_PERMIT,	"trace" },
			{ ACL_PERMIT,	"ui" },
			{ 0 },
		};
		AuthAclDef dptfuiAuth = {
			.name = "dptfui",
			.EsifGetConfig = dptfui_GetConfig,
			.EsifSetConfig = dptfui_SetConfig,
			.EsifPrimitive = dptfui_Primitive,
			.EsifWriteLog = dptfui_WriteLog,
			.EsifEventRegister = dptfui_Event,
			.EsifEventUnregister = dptfui_Event,
			.EsifSendEvent = dptfui_EventSend,
			.EsifSendCommand = dptfui_Command,
		};
		authDef = dptfuiAuth;
		break;
	}

	// IPFUI Role = Innovation Platform Framework UI
	case IPFAUTH_ROLE_IPFUI:
	{
		// Authorized ESIF Interface Parameters for DPTF_UI Role
		static AclConfig ipfui_GetConfig[] = {
			{ 0 },	// Deny All
		};
		static AclConfig ipfui_SetConfig[] = {
			{ 0 },	// Deny All
		};
		static AclPrimitive ipfui_Primitive[] = {
			{ 0 },	// Deny All
		};
		static AclWriteLog ipfui_WriteLog[] = {
			{ ACL_PERMIT }, // Permit All
			{ 0 },
		};
		static AclEvent ipfui_Event[] = {
			{ ACL_PERMIT,	LOG_VERBOSITY_CHANGED },
			{ 0 },
		};
		static AclEvent ipfui_EventSend[] = {
			{ 0 },
		};
		static AclCommand ipfui_Command[] = {
			{ ACL_PERMIT,	"about" },
			{ ACL_PERMIT,	"apps" },
			{ ACL_PERMIT,	"arbitrator" },
			{ ACL_PERMIT,	"config" },
			{ ACL_PERMIT,	"devices" },
			{ ACL_PERMIT,	"echo" },
			{ ACL_PERMIT,	"format" },
			{ ACL_PERMIT,	"getp" },
			{ ACL_PERMIT,	"getp_part" },
			{ ACL_PERMIT,	"participant" },
			{ ACL_PERMIT,	"participantlog" },
			{ ACL_PERMIT,	"participants" },
			{ ACL_PERMIT,	"setp" },
			{ ACL_PERMIT,	"setp_part" },
			{ ACL_PERMIT,	"trace" },
			{ 0 },
		};
		AuthAclDef ipfuiAuth = {
			.name = "ipfui",
			.EsifGetConfig = ipfui_GetConfig,
			.EsifSetConfig = ipfui_SetConfig,
			.EsifPrimitive = ipfui_Primitive,
			.EsifWriteLog = ipfui_WriteLog,
			.EsifEventRegister = ipfui_Event,
			.EsifEventUnregister = ipfui_Event,
			.EsifSendEvent = ipfui_EventSend,
			.EsifSendCommand = ipfui_Command,
		};
		authDef = ipfuiAuth;
		break;
	}

	// ICST Role = Intel Context Sensing Technology (Deprecated)
	case IPFAUTH_ROLE_ICST:	
	{
		// Authorized ESIF Interface Parameters for ICST Role
		static AclConfig icst_GetConfig[] = {
			{ ACL_PERMIT,	"icst" },
			{ 0 },
		};
		static AclConfig icst_SetConfig[] = {
			{ ACL_PERMIT,	"icst" },
			{ 0 },
		};
		static AclPrimitive icst_Primitive[] = {
			{ ACL_PERMIT,	GET_BATTERY_PERCENTAGE },
			{ ACL_PERMIT,	GET_BATTERY_STATUS },
			{ ACL_PERMIT,	GET_BIOMETRIC_PRESENCE_SENSOR_INSTANCE },
			{ ACL_PERMIT,	GET_DISENGAGED_STABILITY_WINDOW },
			{ ACL_PERMIT,	GET_DISPLAY_BRIGHTNESS },
			{ ACL_PERMIT,	GET_DISPLAY_BRIGHTNESS_LEVELS },
			{ ACL_PERMIT,	GET_DISPLAY_BRIGHTNESS_SOFT },
			{ ACL_PERMIT,	GET_DISPLAY_CAPABILITY },
			{ ACL_PERMIT,	GET_DISPLAY_DEPTH_LIMIT },
			{ ACL_PERMIT,	GET_ES_DISPLAY_REQUIRED },
			{ ACL_PERMIT,	GET_IS_BIOMETRIC_PRESENCE_SENSOR_CAPABLE },
			{ ACL_PERMIT,	GET_IS_EXTERNAL_MONITOR_CONNECTED },
			{ ACL_PERMIT,	GET_IS_FACE_DETECTION_CAPABLE },
			{ ACL_PERMIT,	GET_LAST_HID_INPUT_TIME },
			{ ACL_PERMIT,	GET_NEGATIVE_EVENT_FILTERING_STATE },
			{ ACL_PERMIT,	GET_NOT_PRESENT_STABILITY_WINDOW },
			{ ACL_PERMIT,	GET_POSITIVE_EVENT_FILTERING_STATE },
			{ ACL_PERMIT,	GET_PRESENT_STABILITY_WINDOW },
			{ ACL_PERMIT,	SET_BIOMETRIC_PRESENCE_SENSOR_INSTANCE },
			{ ACL_PERMIT,	SET_DISPLAY_BRIGHTNESS },
			{ ACL_PERMIT,	SET_DISPLAY_BRIGHTNESS_SOFT },
			{ ACL_PERMIT,	SET_SCREEN_AUTO_LOCK_STATE },
			{ ACL_PERMIT,	SET_SCREEN_STATE },
			{ ACL_PERMIT,	SET_WAKE_ON_APPROACH_STATE },
			{ ACL_PERMIT,	SET_WORKSTATION_LOCK },
			{ 0 },
		};
		static AclWriteLog icst_WriteLog[] = {
			{ ACL_PERMIT,	eLogTypeFatal,	eLogTypeDebug }, // Permit All
			{ 0 },
		};
		static AclEvent icst_Event[] = {
			{ ACL_PERMIT,	APP_BROADCAST },
			{ ACL_PERMIT,	APP_BROADCAST_UNPRIVILEGED },
			{ ACL_PERMIT,	BIOMETRIC_PRESENCE_SENSOR_DISTANCE_CHANGED },
			{ ACL_PERMIT,	BIOMETRIC_PRESENCE_SENSOR_INSTANCE_CHANGED },
			{ ACL_PERMIT,	BIOMETRIC_PRESENCE_SENSOR_STATUS_CHANGED },
			{ ACL_PERMIT,	BIOMETRIC_PRESENCE_SENSOR_WAKE },
			{ ACL_PERMIT,	DEVICE_ORIENTATION_CHANGED },
			{ ACL_PERMIT,	DISPLAY_OFF },
			{ ACL_PERMIT,	DISPLAY_ON },
			{ ACL_PERMIT,	DTT_DISPLAY_STATUS_CHANGED },
			{ ACL_PERMIT,	EXTERNAL_MONITOR_CONNECTION_STATE_CHANGED },
			{ ACL_PERMIT,	LOG_VERBOSITY_CHANGED },
			{ ACL_PERMIT,	ONLOOKER_SENSOR_HUMAN_COUNT_CHANGED },
			{ ACL_PERMIT,	ONLOOKER_SENSOR_STATUS_CHANGED },
			{ ACL_PERMIT,	OS_BATTERY_PERCENT_CHANGED },
			{ ACL_PERMIT,	OS_DOCK_MODE_CHANGED },
			{ ACL_PERMIT,	OS_GAME_MODE_CHANGED },
			{ ACL_PERMIT,	OS_LID_STATE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SLIDER_VALUE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SOURCE_CHANGED },
			{ ACL_PERMIT,	OS_POWERSCHEME_PERSONALITY_CHANGED },
			{ ACL_PERMIT,	OS_SCREEN_STATE_CHANGED },
			{ ACL_PERMIT,	OS_USER_INTERACTION_CHANGED },
			{ ACL_PERMIT,	OS_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	PLATFORM_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	SENSOR_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	SESSION_STATE_CHANGED },
			{ ACL_PERMIT,	WINDOWS_LOW_POWER_MODE_ENTRY },
			{ ACL_PERMIT,	WINDOWS_LOW_POWER_MODE_EXIT },
			{ 0 },
		};
		static AclEvent icst_EventSend[] = {
			{ 0 },
		};
		static AclCommand icst_Command[] = {
			{ 0 },
		};
		AuthAclDef icstAuth = {
			.name = "icst",
			.EsifGetConfig = icst_GetConfig,
			.EsifSetConfig = icst_SetConfig,
			.EsifPrimitive = icst_Primitive,
			.EsifWriteLog = icst_WriteLog,
			.EsifEventRegister = icst_Event,
			.EsifEventUnregister = icst_Event,
			.EsifSendEvent = icst_EventSend,
			.EsifSendCommand = icst_Command,
		};
		authDef = icstAuth;
		break;
	}

	// ICSTSVC Role = Intel Context Sensing Technology Service
	case IPFAUTH_ROLE_ICSTSVC:
	{
		// Authorized ESIF Interface Parameters for ICSTSVC Role
		static AclConfig icstsvc_GetConfig[] = {
			{ ACL_PERMIT,	"icst" },
			{ 0 },
		};
		static AclConfig icstsvc_SetConfig[] = {
			{ ACL_PERMIT,	"icst" },
			{ 0 },
		};
		static AclPrimitive icstsvc_Primitive[] = {
			{ ACL_PERMIT,	GET_BATTERY_PERCENTAGE },
			{ ACL_PERMIT,	GET_BATTERY_STATUS },
			{ ACL_PERMIT,	GET_BIOMETRIC_PRESENCE_SENSOR_INSTANCE },
			{ ACL_PERMIT,	GET_DISENGAGED_STABILITY_WINDOW },
			{ ACL_PERMIT,	GET_DISPLAY_BRIGHTNESS },
			{ ACL_PERMIT,	GET_DISPLAY_BRIGHTNESS_LEVELS },
			{ ACL_PERMIT,	GET_DISPLAY_BRIGHTNESS_SOFT },
			{ ACL_PERMIT,	GET_DISPLAY_CAPABILITY },
			{ ACL_PERMIT,	GET_DISPLAY_DEPTH_LIMIT },
			{ ACL_PERMIT,	GET_ES_DISPLAY_REQUIRED },
			{ ACL_PERMIT,	GET_IS_BIOMETRIC_PRESENCE_SENSOR_CAPABLE },
			{ ACL_PERMIT,	GET_IS_EXTERNAL_MONITOR_CONNECTED },
			{ ACL_PERMIT,	GET_IS_FACE_DETECTION_CAPABLE },
			{ ACL_PERMIT,	GET_LAST_HID_INPUT_TIME },
			{ ACL_PERMIT,	GET_NEGATIVE_EVENT_FILTERING_STATE },
			{ ACL_PERMIT,	GET_NOT_PRESENT_STABILITY_WINDOW },
			{ ACL_PERMIT,	GET_POSITIVE_EVENT_FILTERING_STATE },
			{ ACL_PERMIT,	GET_PRESENT_STABILITY_WINDOW },
			{ ACL_PERMIT,	GET_USER_BASED_REFRESH_RATE },
			{ ACL_PERMIT,	GET_USER_BASED_REFRESH_RATE_CAPABILITY },
			{ ACL_PERMIT,	SET_BIOMETRIC_PRESENCE_SENSOR_INSTANCE },
			{ ACL_PERMIT,	SET_DISPLAY_BRIGHTNESS },
			{ ACL_PERMIT,	SET_DISPLAY_BRIGHTNESS_SOFT },
			{ ACL_PERMIT,	SET_SCREEN_AUTO_LOCK_STATE },
			{ ACL_PERMIT,	SET_SCREEN_STATE },
			{ ACL_PERMIT,	SET_USER_BASED_REFRESH_RATE },
			{ ACL_PERMIT,	SET_WAKE_ON_APPROACH_STATE },
			{ ACL_PERMIT,	SET_WORKSTATION_LOCK },
			{ 0 },
		};
		static AclWriteLog icstsvc_WriteLog[] = {
			{ ACL_PERMIT,	eLogTypeFatal,	eLogTypeDebug }, // Permit All
			{ 0 },
		};
		static AclEvent icstsvc_Event[] = {
			{ ACL_PERMIT,	APP_BROADCAST },
			{ ACL_PERMIT,	APP_BROADCAST_UNPRIVILEGED },
			{ ACL_PERMIT,	BIOMETRIC_PRESENCE_SENSOR_DISTANCE_CHANGED },
			{ ACL_PERMIT,	BIOMETRIC_PRESENCE_SENSOR_INSTANCE_CHANGED },
			{ ACL_PERMIT,	BIOMETRIC_PRESENCE_SENSOR_STATUS_CHANGED },
			{ ACL_PERMIT,	BIOMETRIC_PRESENCE_SENSOR_WAKE },
			{ ACL_PERMIT,	DEVICE_ORIENTATION_CHANGED },
			{ ACL_PERMIT,	DISPLAY_OFF },
			{ ACL_PERMIT,	DISPLAY_ON },
			{ ACL_PERMIT,	DTT_DISPLAY_STATUS_CHANGED },
			{ ACL_PERMIT,	EXTERNAL_MONITOR_CONNECTION_STATE_CHANGED },
			{ ACL_PERMIT,	FACE_ID_CAPABILITY_SUPPORT_CHANGED },
			{ ACL_PERMIT,	LOG_VERBOSITY_CHANGED },
			{ ACL_PERMIT,	NUM_FACES_ENROLLED_CHANGED },
			{ ACL_PERMIT,	ONLOOKER_SENSOR_HUMAN_COUNT_CHANGED },
			{ ACL_PERMIT,	ONLOOKER_SENSOR_STATUS_CHANGED },
			{ ACL_PERMIT,	OS_BATTERY_PERCENT_CHANGED },
			{ ACL_PERMIT,	OS_DOCK_MODE_CHANGED },
			{ ACL_PERMIT,	OS_GAME_MODE_CHANGED },
			{ ACL_PERMIT,	OS_LID_STATE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SLIDER_VALUE_CHANGED },
			{ ACL_PERMIT,	OS_POWER_SOURCE_CHANGED },
			{ ACL_PERMIT,	OS_POWERSCHEME_PERSONALITY_CHANGED },
			{ ACL_PERMIT,	OS_SCREEN_STATE_CHANGED },
			{ ACL_PERMIT,	OS_USER_INTERACTION_CHANGED },
			{ ACL_PERMIT,	OS_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	PLATFORM_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	SENSOR_USER_PRESENCE_CHANGED },
			{ ACL_PERMIT,	SESSION_STATE_CHANGED },
			{ ACL_PERMIT,	WINDOWS_LOW_POWER_MODE_ENTRY },
			{ ACL_PERMIT,	WINDOWS_LOW_POWER_MODE_EXIT },
			{ 0 },
		};
		static AclEvent icstsvc_EventSend[] = {
			{ ACL_PERMIT,	APP_BROADCAST },
			{ 0 },
		};
		static AclCommand icstsvc_Command[] = {
			{ 0 },
		};
		AuthAclDef icstsvcAuth = {
			.name = "icstsvc",
			.EsifGetConfig = icstsvc_GetConfig,
			.EsifSetConfig = icstsvc_SetConfig,
			.EsifPrimitive = icstsvc_Primitive,
			.EsifWriteLog = icstsvc_WriteLog,
			.EsifEventRegister = icstsvc_Event,
			.EsifEventUnregister = icstsvc_Event,
			.EsifSendEvent = icstsvc_EventSend,
			.EsifSendCommand = icstsvc_Command,
		};
		authDef = icstsvcAuth;
		break;
	}

	// NONE Role = No Access to any ESIF Interface Functions
	case IPFAUTH_ROLE_NONE:
	default:
		break;
	}
	return authDef;
}

esif_error_t AuthMgr_Init(void)
{
	AuthMgr *self = &g_AuthMgr;
	if (self) {
		for (u64 j = 0; j < IPFAUTH_MAX_ROLES; j++) {
			esif_handle_t roleId = IPFAUTH_ROLE_NONE + j;
			self->roles[IPFAUTH_ROLE_INDEX(roleId)] = AuthMgr_GetAuthAclDef(roleId);
		}
	}
	return ESIF_OK;
}

void AuthMgr_Exit(void)
{
}

// Get Authentication Role Handle for an IPF Session by ESIF Handle
esif_handle_t AuthMgr_GetAuthHandleByEsifHandle(esif_handle_t esifHandle)
{
	AuthMgr *self = &g_AuthMgr;
	esif_handle_t authHandle = IPFAUTH_ROLE_NONE;
	AppSession *session = AppSessionMgr_GetSessionByEsifHandle(esifHandle);
	if (self && session) {
		if (session->authHandle != ESIF_INVALID_HANDLE) {
			authHandle = session->authHandle;
		}
		AppSession_PutRef(session);
	}
	return authHandle;
}

// Get Authentication ACLs for an IPF Session by ESIF Handle
AuthAclDef *AuthMgr_GetAuthAclByEsifHandle(esif_handle_t esifHandle)
{
	AuthMgr *self = &g_AuthMgr;
	AuthAclDef *auth = NULL;
	if (self) {
		esif_handle_t authHandle = AuthMgr_GetAuthHandleByEsifHandle(esifHandle);
		if (authHandle != ESIF_INVALID_HANDLE) {
			auth = &self->roles[IPFAUTH_ROLE_INDEX(authHandle)];
		}
	}
	return auth;
}

// Get Authentication Role Handle Description for an IPF Session by ESIF Handle
esif_string AuthMgr_GetAuthNameByEsifHandle(esif_handle_t esifHandle)
{
	esif_string name = "none";
	AuthAclDef *auth = AuthMgr_GetAuthAclByEsifHandle(esifHandle);
	if (auth && auth->name[0]) {
		name = auth->name;
	}
	return name;
}

// Get Authentication Role Handle Description for an IPF Session by Auth Handle
esif_string AuthMgr_GetAuthNameByAuthHandle(esif_handle_t authHandle)
{
	esif_string name = "none";
	AuthMgr* self = &g_AuthMgr;
	if (self) {
		name = self->roles[IPFAUTH_ROLE_INDEX(authHandle)].name;
	}
	return name;
}

//////////////////////////////////////////////////////////////////////////////
// Access Control List ESIF Interface Functions
// These functions are the lowest level of ESIF Interface functions called
// within IPFSRV before the actual ESIF Interface functions are called.
// The esifHandle passed to these functions is the handle generated by ESIF.
//////////////////////////////////////////////////////////////////////////////

// Authorization Function for ESIF GetConfig requests sent from IPF Clients
esif_error_t ESIF_CALLCONV AuthMgr_EsifGetConfig(
	const esif_handle_t esifHandle,
	const EsifDataPtr nameSpace,
	const EsifDataPtr elementPath,
	EsifDataPtr elementValue)
{
	esif_error_t rc = ESIF_E_NOT_IMPLEMENTED;
	AuthAclDef *auth = AuthMgr_GetAuthAclByEsifHandle(esifHandle);
	AclConfig nullAuth = { 0 };
	Bool isAuthorized = IPF_AUTH_DEFAULT;

	if (nameSpace && nameSpace->buf_ptr && elementPath && elementPath->buf_ptr) {
		for (size_t j = 0; auth && IPF_ACL_HASDATA(auth->EsifGetConfig); j++) {
			if ((auth->EsifGetConfig[j].nameSpace == NULL || esif_ccb_strmatch(nameSpace->buf_ptr, auth->EsifGetConfig[j].nameSpace) == ESIF_TRUE) &&
				(auth->EsifGetConfig[j].keyName == NULL || esif_ccb_strmatch(elementPath->buf_ptr, auth->EsifGetConfig[j].keyName) == ESIF_TRUE)) {
				isAuthorized = auth->EsifGetConfig[j].permit;
				break;
			}
		}
	}

	// Deny Access or Call into Native ESIF Interface Function
	if (!isAuthorized) {
		IPF_TRACE_ERROR("\nUnauthorized EsifGetConfig: %s:%s\n", (char *)(nameSpace ? nameSpace->buf_ptr : NULL), (char *)(elementPath ? elementPath->buf_ptr : NULL));
		rc = ESIF_E_SESSION_PERMISSION_DENIED;
	}
	else {
		if (IpfSrv_GetInterface().esifIface.fGetConfigFuncPtr) {
			rc = IpfSrv_GetInterface().esifIface.fGetConfigFuncPtr(
				esifHandle,
				nameSpace,
				elementPath,
				elementValue
			);
		}
	}
	return rc;
}

// Authorization Function for ESIF SetConfig requests sent from IPF Clients
esif_error_t ESIF_CALLCONV AuthMgr_EsifSetConfig(
	const esif_handle_t esifHandle,
	const EsifDataPtr nameSpace,
	const EsifDataPtr elementPath,
	EsifDataPtr elementValue,
	const EsifFlags elementFlags)
{
	esif_error_t rc = ESIF_E_NOT_IMPLEMENTED;
	AuthAclDef *auth = AuthMgr_GetAuthAclByEsifHandle(esifHandle);
	AclConfig nullAuth = { 0 };
	Bool isAuthorized = IPF_AUTH_DEFAULT;

	if (nameSpace && nameSpace->buf_ptr && elementPath && elementPath->buf_ptr) {
		for (size_t j = 0; auth && IPF_ACL_HASDATA(auth->EsifSetConfig); j++) {
			if ((auth->EsifSetConfig[j].nameSpace == NULL || esif_ccb_strmatch(nameSpace->buf_ptr, auth->EsifSetConfig[j].nameSpace) == ESIF_TRUE) &&
				(auth->EsifSetConfig[j].keyName == NULL || esif_ccb_strmatch(elementPath->buf_ptr, auth->EsifSetConfig[j].keyName) == ESIF_TRUE)) {
				isAuthorized = auth->EsifSetConfig[j].permit;
				break;
			}
		}
	}

	// Deny Access or Call into Native ESIF Interface Function
	if (!isAuthorized) {
		IPF_TRACE_ERROR("\nUnauthorized EsifSetConfig: %s:%s\n", (char *)(nameSpace ? nameSpace->buf_ptr : NULL), (char *)(elementPath ? elementPath->buf_ptr : NULL));
		rc = ESIF_E_SESSION_PERMISSION_DENIED;
	}
	else {
		if (IpfSrv_GetInterface().esifIface.fSetConfigFuncPtr) {
			rc = IpfSrv_GetInterface().esifIface.fSetConfigFuncPtr(
				esifHandle,
				nameSpace,
				elementPath,
				elementValue,
				elementFlags
			);
		}
	}
	return rc;
}

// Authorization Function for ESIF Primitives requests sent from IPF Clients
esif_error_t ESIF_CALLCONV AuthMgr_EsifPrimitive(
	const esif_handle_t esifHandle,
	const esif_handle_t participantHandle,
	const esif_handle_t domainHandle,
	const EsifDataPtr request,
	EsifDataPtr response,
	const ePrimitiveType primitive,
	const UInt8 instance)
{
	esif_error_t rc = ESIF_E_NOT_IMPLEMENTED;
	AuthAclDef *auth = AuthMgr_GetAuthAclByEsifHandle(esifHandle);
	AclPrimitive nullAuth = { 0 };
	Bool isAuthorized = IPF_AUTH_DEFAULT;

	for (size_t j = 0; auth && IPF_ACL_HASDATA(auth->EsifPrimitive); j++) {
		if (auth->EsifPrimitive[j].primitiveId == primitive || auth->EsifPrimitive[j].primitiveId == (esif_primitive_type_t)(0)) {
			isAuthorized = auth->EsifPrimitive[j].permit;
			break;
		}
	}

	// Deny Access or Call into Native ESIF Interface Function
	if (!isAuthorized) {
		IPF_TRACE_ERROR("\nUnauthorized EsifPrimitive: %s (%d)\n", esif_primitive_str(primitive), (int)primitive);
		rc = ESIF_E_SESSION_PERMISSION_DENIED;
	}
	else {
		if (IpfSrv_GetInterface().esifIface.fPrimitiveFuncPtr) {
			rc = IpfSrv_GetInterface().esifIface.fPrimitiveFuncPtr(
				esifHandle,
				participantHandle,
				domainHandle,
				request,
				response,
				primitive,
				instance
			);

			// Workaround for Actions that return basic data types (UINT32, POWER, etc) but set data_len=0:
			// Set data_len = basic type length if Action returns OK and a large enough buf_ptr and buf_len
			UInt32 basictype_len = (UInt32)(response ? esif_data_type_sizeof(response->type) : 0);
			if (rc == ESIF_OK && response && response->data_len == 0 && basictype_len && response->buf_len >= basictype_len) {
				response->data_len = basictype_len;
			}
		}
	}
	return rc;
}

// Authorization Function for ESIF Primitives requests sent from IPF Clients
esif_error_t ESIF_CALLCONV AuthMgr_EsifWriteLog(
	const esif_handle_t esifHandle,
	const esif_handle_t participantHandle,
	const esif_handle_t domainHandle,
	const EsifDataPtr message,
	const eLogType logType)
{
	esif_error_t rc = ESIF_E_NOT_IMPLEMENTED;
	AuthAclDef *auth = AuthMgr_GetAuthAclByEsifHandle(esifHandle);
	AclWriteLog nullAuth = { 0 };
	Bool isAuthorized = IPF_AUTH_DEFAULT;

	for (size_t j = 0; auth && IPF_ACL_HASDATA(auth->EsifWriteLog); j++) {
		if ((logType >= auth->EsifWriteLog[j].minLogType && logType <= auth->EsifWriteLog[j].maxLogType && auth->EsifWriteLog[j].maxLogType > eLogTypeFatal) ||
			(auth->EsifWriteLog[j].minLogType == eLogTypeFatal && auth->EsifWriteLog[j].maxLogType == eLogTypeFatal)) {
			isAuthorized = auth->EsifWriteLog[j].permit;
			break;
		}
	}

	// Deny Access or Call into Native ESIF Interface Function
	if (!isAuthorized) {
		IPF_TRACE_ERROR("\nUnauthorized EsifWriteLog: (%d)\n", logType);
		rc = ESIF_E_SESSION_PERMISSION_DENIED;
	}
	else {
		if (IpfSrv_GetInterface().esifIface.fWriteLogFuncPtr) {
			rc = IpfSrv_GetInterface().esifIface.fWriteLogFuncPtr(
				esifHandle,
				participantHandle,
				domainHandle,
				message,
				logType
			);
		}
	}
	return rc;
}

// Authorization Function for ESIF EventRegister requests sent from IPF Clients
esif_error_t ESIF_CALLCONV AuthMgr_EsifEventRegister(
	const esif_handle_t esifHandle,
	const esif_handle_t participantHandle,
	const esif_handle_t domainHandle,
	const EsifDataPtr eventGuid)
{
	esif_error_t rc = ESIF_E_NOT_IMPLEMENTED;
	AuthAclDef *auth = AuthMgr_GetAuthAclByEsifHandle(esifHandle);
	AclEvent nullAuth = { 0 };
	esif_guid_t nullGuid = { 0 };
	esif_guid_t theguid = { 0 };
	Bool isAuthorized = IPF_AUTH_DEFAULT;

	if (eventGuid && eventGuid->buf_ptr && eventGuid->data_len == sizeof(esif_guid_t)) {
		for (size_t j = 0; auth && IPF_ACL_HASDATA(auth->EsifEventRegister); j++) {
			if ((memcmp(auth->EsifEventRegister[j].guid, nullGuid, sizeof(esif_guid_t)) == 0) ||
				(memcmp(auth->EsifEventRegister[j].guid, eventGuid->buf_ptr, sizeof(esif_guid_t)) == 0)) {
				isAuthorized = auth->EsifEventRegister[j].permit;
				break;
			}
		}
		esif_ccb_memcpy(theguid, eventGuid->buf_ptr, sizeof(esif_guid_t));
	}

	// Deny Access or Call into Native ESIF Interface Function
	if (!isAuthorized) {
		char guidstr[ESIF_GUIDSTR_LEN] = {0};
		esif_event_type_t type = (esif_event_type_t)(-1);
		esif_event_map_guid2type(&theguid, &type);
		IPF_TRACE_ERROR("\nUnauthorized EsifEventRegister: %s (%d) [%s]\n", esif_event_type_str(type), type, esif_guid_tostring(theguid, guidstr, sizeof(guidstr)));
		rc = ESIF_E_SESSION_PERMISSION_DENIED;
	}
	else {
		if (IpfSrv_GetInterface().esifIface.fRegisterEventFuncPtr) {
			rc = IpfSrv_GetInterface().esifIface.fRegisterEventFuncPtr(
				esifHandle,
				participantHandle,
				domainHandle,
				eventGuid
			);
		}
	}
	return rc;
}

// Authorization Function for ESIF EventUnregister requests sent from IPF Clients
esif_error_t ESIF_CALLCONV AuthMgr_EsifEventUnregister(
	const esif_handle_t esifHandle,
	const esif_handle_t participantHandle,
	const esif_handle_t domainHandle,
	const EsifDataPtr eventGuid)
{
	esif_error_t rc = ESIF_E_NOT_IMPLEMENTED;
	AuthAclDef *auth = AuthMgr_GetAuthAclByEsifHandle(esifHandle);
	AclEvent nullAuth = { 0 };
	esif_guid_t nullGuid = { 0 };
	esif_guid_t theguid = { 0 };
	Bool isAuthorized = IPF_AUTH_DEFAULT;

	if (eventGuid && eventGuid->buf_ptr && eventGuid->data_len == sizeof(esif_guid_t)) {
		for (size_t j = 0; auth && IPF_ACL_HASDATA(auth->EsifEventUnregister); j++) {
			if ((memcmp(auth->EsifEventUnregister[j].guid, nullGuid, sizeof(esif_guid_t)) == 0) ||
				(memcmp(auth->EsifEventUnregister[j].guid, eventGuid->buf_ptr, sizeof(esif_guid_t)) == 0)) {
				isAuthorized = auth->EsifEventUnregister[j].permit;
				break;
			}
		}
		esif_ccb_memcpy(theguid, eventGuid->buf_ptr, sizeof(esif_guid_t));
	}

	// Deny Access or Call into Native ESIF Interface Function
	if (!isAuthorized) {
		char guidstr[ESIF_GUIDSTR_LEN] = {0};
		esif_event_type_t type = (esif_event_type_t)(-1);
		esif_event_map_guid2type(&theguid, &type);
		IPF_TRACE_ERROR("\nUnauthorized EsifEventUnregister: %s (%d) [%s]\n", esif_event_type_str(type), type, esif_guid_tostring(theguid, guidstr, sizeof(guidstr)));
		rc = ESIF_E_SESSION_PERMISSION_DENIED;
	}
	else {
		if (IpfSrv_GetInterface().esifIface.fUnregisterEventFuncPtr) {
			rc = IpfSrv_GetInterface().esifIface.fUnregisterEventFuncPtr(
				esifHandle,
				participantHandle,
				domainHandle,
				eventGuid
			);
		}
	}
	return rc;
}

// Authorization Function for ESIF SendEvent requests sent from IPF Clients
esif_error_t ESIF_CALLCONV AuthMgr_EsifSendEvent(
	const esif_handle_t esifHandle,
	const esif_handle_t participantHandle,
	const esif_handle_t domainHandle,
	const EsifDataPtr eventData,
	const EsifDataPtr eventGuid)
{
	esif_error_t rc = ESIF_E_NOT_IMPLEMENTED;
	AuthAclDef *auth = AuthMgr_GetAuthAclByEsifHandle(esifHandle);
	AclEvent nullAuth = { 0 };
	esif_guid_t nullGuid = { 0 };
	Bool isAuthorized = IPF_AUTH_DEFAULT;

	if (eventGuid && eventGuid->buf_ptr && eventGuid->data_len == sizeof(esif_guid_t)) {
		for (size_t j = 0; auth && IPF_ACL_HASDATA(auth->EsifSendEvent); j++) {
			if ((memcmp(auth->EsifSendEvent[j].guid, nullGuid, sizeof(esif_guid_t)) == 0) ||
				(memcmp(auth->EsifSendEvent[j].guid, eventGuid->buf_ptr, sizeof(esif_guid_t)) == 0)) {
				isAuthorized = auth->EsifSendEvent[j].permit;
				break;
			}
		}
	}

	// Deny Access or Call into Native ESIF Interface Function
	if (!isAuthorized) {
		esif_event_type_t type = (esif_event_type_t)(-1);
		esif_event_map_guid2type((esif_guid_t *)(eventGuid ? eventGuid->buf_ptr : NULL), &type);
		IPF_TRACE_ERROR("\nUnauthorized EsifSendEvent: %s\n", esif_event_type_str(type));
		rc = ESIF_E_SESSION_PERMISSION_DENIED;
	}
	else {
		if (IpfSrv_GetInterface().esifIface.fSendEventFuncPtr) {
			rc = IpfSrv_GetInterface().esifIface.fSendEventFuncPtr(
				esifHandle,
				participantHandle,
				domainHandle,
				eventData,
				eventGuid
			);
		}
	}
	return rc;
}

// Authorization Function for ESIF GetConfig requests sent from IPF Clients
esif_error_t ESIF_CALLCONV AuthMgr_EsifSendCommand(
	const esif_handle_t esifHandle,
	const UInt32 argc,
	const EsifDataArray argv,
	EsifDataPtr response)
{
	esif_error_t rc = ESIF_E_NOT_IMPLEMENTED;
	AuthAclDef *auth = AuthMgr_GetAuthAclByEsifHandle(esifHandle);
	AclCommand nullAuth = { 0 };
	Bool isAuthorized = IPF_AUTH_DEFAULT;

	if (argc && argv && argv[0].buf_ptr) {
		esif_string thiscmd = (esif_string)argv[0].buf_ptr;
		do {
			// Verify base command is permitted
			for (size_t j = 0; argc && auth && IPF_ACL_HASDATA(auth->EsifSendCommand); j++) {
				size_t cmdlen = esif_ccb_strlen(auth->EsifSendCommand[j].command, MAX_PATH);
				if ((auth->EsifSendCommand[j].command == NULL) ||
					(esif_ccb_strnicmp(auth->EsifSendCommand[j].command, thiscmd, cmdlen) == 0 && (thiscmd[cmdlen] == 0 || isspace(thiscmd[cmdlen])))) {
					isAuthorized = auth->EsifSendCommand[j].permit;
					break;
				}
			}

			// Skip command separator and verify next command, if any
			if (!isAuthorized) {
				thiscmd = NULL;
			}
			else {
				const char cmdsep[] = " && ";
				if ((thiscmd = esif_ccb_strstr(thiscmd, cmdsep)) != NULL) {
					thiscmd += sizeof(cmdsep) - 1;
					isAuthorized = IPF_AUTH_DEFAULT;
					while (isspace(*thiscmd)) {
						thiscmd++;
					}
				}
			}
		} while (thiscmd != NULL);
	}

	// Deny Access or Call into Native ESIF Interface Function
	if (!isAuthorized) {
		IPF_TRACE_ERROR("\nUnauthorized EsifSendCommand '%s'\n", (esif_string)(argv && argc ? argv[0].buf_ptr : NULL));
		rc = ESIF_E_SESSION_PERMISSION_DENIED;
	}
	else {
		if (IpfSrv_GetInterface().esifIface.fSendCommandFuncPtr) {
			rc = IpfSrv_GetInterface().esifIface.fSendCommandFuncPtr(
				esifHandle,
				argc,
				argv,
				response
			);
		}
	}
	return rc;
}
