/*******************************************************************************
** This file is provided under a dual BSD/GPLv2 license.  When using or
** redistributing this file, you may do so under either license.
**
** GPL LICENSE SUMMARY
**
** Copyright (c) 2013-2022 Intel Corporation All Rights Reserved
**
** This program is free software; you can redistribute it and/or modify it under
** the terms of version 2 of the GNU General Public License as published by the
** Free Software Foundation.
**
** This program is distributed in the hope that it will be useful, but WITHOUT
** ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
** FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
** details.
**
** You should have received a copy of the GNU General Public License along with
** this program; if not, write to the Free Software  Foundation, Inc.,
** 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
** The full GNU General Public License is included in this distribution in the
** file called LICENSE.GPL.
**
** BSD LICENSE
**
** Copyright (c) 2013-2022 Intel Corporation All Rights Reserved
**
** Redistribution and use in source and binary forms, with or without
** modification, are permitted provided that the following conditions are met:
**
** * Redistributions of source code must retain the above copyright notice, this
**   list of conditions and the following disclaimer.
** * Redistributions in binary form must reproduce the above copyright notice,
**   this list of conditions and the following disclaimer in the documentation
**   and/or other materials provided with the distribution.
** * Neither the name of Intel Corporation nor the names of its contributors may
**   be used to endorse or promote products derived from this software without
**   specific prior written permission.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
** AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
** ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
** LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,  SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
**
*******************************************************************************/

#pragma once

#include "esif_sdk.h"

/* Definitions not moved to esif_ccb.h or esif_sdk.h */

/* Build option to enable simulation support */
/* #define ESIF_FEAT_OPT_SIM_SUPPORT_ENABLED */

/* Build option to enable the primitive arbitrator */
#define ESIF_FEAT_OPT_ARBITRATOR_ENABLED  

/* Build option to enable event caching */
#define ESIF_FEAT_OPT_EVENT_CACHE_ENABLED

/* IPF core and IPC layer tracing support */
#define ESIF_FEAT_OPT_IPF_CLIENT_ETW_TRACE_ENABLED



/*
 * ESIF_FEAT_OPT_SYSFS exports SYSFS entries. It is defined
 * in ESIF_LF/Linuxx64/Debug/makefile and
 * ESIF_LF/Linuxx64/Release/makefile. It is disabled by default.
 * To enable it, it must be uncommented out in makefile.
 */





/*
 * OS Agnostic
 */

/* Linux */
#include <fcntl.h>
#include <sys/ioctl.h>



typedef esif_string EsifString;

#define ESIF_PERCENT_CONV_FACTOR 100 /* Percentages are in 100ths */

#define ESIF_PLATFORM_MSG "Registering Platform Driver"
#define ESIF_LICENSE "Dual BSD/GPL"
#define ESIF_AUTHOR  "Intel Corporation <dptf@lists.01.org>"

/*
 * Common Code Base - OS/Platform Abstraction layer
 */
#include "esif_ccb_rc.h"	/* Return Codes     */


#include <stdlib.h>		/* Standard Library */
#include <string.h>		/* String Library   */
#include "esif_ccb_thread.h"
#include "esif_ccb_library.h"
#include "esif_ccb_file.h"


#include "esif_ccb_lock.h"
#include "esif_ccb_mempool.h"
#include "esif_ccb_memstat.h"
#include "esif_ccb_memory.h"
#include "esif_ccb_time.h"
#include "esif_ccb_string.h"
#include "esif_ccb_sem.h"
#include "esif_ccb_timer.h"


/*
 * Autogenerated Data Types
 */

/* Autogen Types Required for Upper Framework */
#include "esif_enum_algorithm_type.h"
#include "esif_enum_acpi_device.h"
#include "esif_enum_event_group.h"
#include "esif_enum_pci_device.h"
#include "esif_enum_vendor_type.h"
#include "esif_sdk_action_type.h"
#include "esif_sdk_capability_type.h"
#include "esif_sdk_class_guid.h"
#include "esif_sdk_data.h"
#include "esif_sdk_data_misc.h"
#include "esif_sdk_domain_type.h"
#include "esif_sdk_event_type.h"
#include "esif_sdk_event_map.h"
#include "esif_sdk_iface.h"
#include "esif_sdk_iface_app.h"
#include "esif_sdk_iface_esif.h"
#include "esif_sdk_participant_enum.h"
#include "esif_sdk_primitive_type.h"
#include "esif_sdk_logging_data.h"
#include "esif_uf.h"



/* OS Agnostic */
#include "esif_mempool.h"	/* Memory Pool      */

/* Opaque Types */
typedef u32 esif_temp_t;	/* Temperature  */
typedef u32 esif_power_t;	/* Power        */
typedef u32 esif_time_t;	/* Time         */
