/*******************************************************************************
** This file is provided under a dual BSD/GPLv2 license.  When using or
** redistributing this file, you may do so under either license.
**
** GPL LICENSE SUMMARY
**
** Copyright (c) 2013-2020 Intel Corporation All Rights Reserved
**
** This program is free software; you can redistribute it and/or modify it under
** the terms of version 2 of the GNU General Public License as published by the
** Free Software Foundation.
**
** This program is distributed in the hope that it will be useful, but WITHOUT
** ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
** FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
** details.
**
** You should have received a copy of the GNU General Public License along with
** this program; if not, write to the Free Software  Foundation, Inc.,
** 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
** The full GNU General Public License is included in this distribution in the
** file called LICENSE.GPL.
**
** BSD LICENSE
**
** Copyright (c) 2013-2020 Intel Corporation All Rights Reserved
**
** Redistribution and use in source and binary forms, with or without
** modification, are permitted provided that the following conditions are met:
**
** * Redistributions of source code must retain the above copyright notice, this
**   list of conditions and the following disclaimer.
** * Redistributions in binary form must reproduce the above copyright notice,
**   this list of conditions and the following disclaimer in the documentation
**   and/or other materials provided with the distribution.
** * Neither the name of Intel Corporation nor the names of its contributors may
**   be used to endorse or promote products derived from this software without
**   specific prior written permission.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
** AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
** ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
** LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,  SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
**
*******************************************************************************/

#pragma once

#include "esif_sdk.h"

/*
* Event Types
*/

/* Event Priority */
typedef enum esif_event_priority {
	ESIF_EVENT_PRIORITY_NORMAL = 0,
	ESIF_EVENT_PRIORITY_LOW = 1,
	ESIF_EVENT_PRIORITY_HIGH = 2,
} esif_event_priority_t;

/* Event Priority String */
static ESIF_INLINE char *
esif_event_priority_str(esif_event_priority_t priority)
{
	switch (priority) {
	ESIF_CASE_ENUM(ESIF_EVENT_PRIORITY_NORMAL);
	ESIF_CASE_ENUM(ESIF_EVENT_PRIORITY_LOW);
	ESIF_CASE_ENUM(ESIF_EVENT_PRIORITY_HIGH);
	}
	return ESIF_NOT_AVAILABLE;
}


/* Event Type */
typedef enum esif_event_type {
	ESIF_EVENT_APP_CONNECTED_STANDBY_ENTRY = 0,
	ESIF_EVENT_APP_CONNECTED_STANDBY_EXIT = 1,
	ESIF_EVENT_APP_ACTIVE_RELATIONSHIP_CHANGED = 2,
	ESIF_EVENT_APP_THERMAL_RELATIONSHIP_CHANGED = 3,
	ESIF_EVENT_APP_FOREGROUND_CHANGED = 4,
	ESIF_EVENT_PARTICIPANT_SUSPEND = 5,
	ESIF_EVENT_PARTICIPANT_RESUME = 6,
	ESIF_EVENT_DOMAIN_CORE_CAPABILITY_CHANGED = 8,
	ESIF_EVENT_DOMAIN_DISPLAY_CAPABILITY_CHANGED = 9,
	ESIF_EVENT_DOMAIN_DISPLAY_STATUS_CHANGED = 10,
	ESIF_EVENT_DOMAIN_PERF_CAPABILITY_CHANGED = 11,
	ESIF_EVENT_DOMAIN_PERF_CONTROL_CHANGED = 12,
	ESIF_EVENT_DOMAIN_POWER_CAPABILITY_CHANGED = 13,
	ESIF_EVENT_DOMAIN_POWER_THRESHOLD_CROSSED = 14,
	ESIF_EVENT_DOMAIN_PRIORITY_CHANGED = 15,
	ESIF_EVENT_DOMAIN_TEMP_THRESHOLD_CROSSED = 16,
	ESIF_EVENT_PARTICIPANT_SPEC_INFO_CHANGED = 17,
	ESIF_EVENT_PARTICIPANT_CREATE = 18,
	ESIF_EVENT_PARTICIPANT_UNREGISTER = 19,
	ESIF_EVENT_PARTICIPANT_SHUTDOWN = 20,
	ESIF_EVENT_ACPI = 21,
	ESIF_EVENT_PASSIVE_TABLE_CHANGED = 24,
	ESIF_EVENT_DISPLAY_ORIENTATION_CHANGED = 26,
	ESIF_EVENT_DEVICE_ORIENTATION_CHANGED = 27,
	ESIF_EVENT_MOTION_CHANGED = 28,
	ESIF_EVENT_SYSTEM_COOLING_POLICY_CHANGED = 29,
	ESIF_EVENT_RF_PROFILE_CHANGED = 32,
	ESIF_EVENT_RF_CONNECTION_STATUS_CHANGED = 33,
	ESIF_EVENT_LOG_VERBOSITY_CHANGED = 34,
	ESIF_EVENT_POWER_SOURCE_CHANGED = 37,
	ESIF_EVENT_TEMP_THRESHOLD_INTERRUPT = 39,
	ESIF_EVENT_DRIVER_SUSPEND = 40,
	ESIF_EVENT_DRIVER_RESUME = 41,
	ESIF_EVENT_ADAPTIVE_PERFORMANCE_CONDITIONS_TABLE_CHANGED = 42,
	ESIF_EVENT_ADAPTIVE_PERFORMANCE_ACTIONS_TABLE_CHANGED = 43,
	ESIF_EVENT_OS_POWER_SOURCE_CHANGED = 44,
	ESIF_EVENT_OS_LID_STATE_CHANGED = 45,
	ESIF_EVENT_OS_BATTERY_PERCENT_CHANGED = 46,
	ESIF_EVENT_OS_PLATFORM_TYPE_CHANGED = 47,
	ESIF_EVENT_OS_DOCK_MODE_CHANGED = 48,
	ESIF_EVENT_OEM_VARS_CHANGED = 49,
	ESIF_EVENT_DOMAIN_VIRTUAL_SENSOR_CALIB_TABLE_CHANGED = 50,
	ESIF_EVENT_DOMAIN_VIRTUAL_SENSOR_POLLING_TABLE_CHANGED = 51,
	ESIF_EVENT_DOMAIN_VIRTUAL_SENSOR_RECALC_CHANGED = 52,
	ESIF_EVENT_DOMAIN_BATTERY_STATUS_CHANGED = 54,
	ESIF_EVENT_DOMAIN_BATTERY_INFORMATION_CHANGED = 55,
	ESIF_EVENT_DOMAIN_PLATFORM_BATTERY_STEADY_STATE_CHANGED = 56,
	ESIF_EVENT_DOMAIN_PLATFORM_POWER_SOURCE_CHANGED = 57,
	ESIF_EVENT_DOMAIN_CHARGER_TYPE_CHANGED = 59,
	ESIF_EVENT_DOMAIN_PLATFORM_REST_OF_POWER_CHANGED = 60,
	ESIF_EVENT_POWER_BOSS_CONDITIONS_TABLE_CHANGED = 63,
	ESIF_EVENT_POWER_BOSS_ACTIONS_TABLE_CHANGED = 64,
	ESIF_EVENT_DPTF_POLICY_LOADED_UNLOADED = 65,
	ESIF_EVENT_DPTF_POLICY_ACTIVITY_LOGGING_ENABLED = 66,
	ESIF_EVENT_DPTF_POLICY_ACTIVITY_LOGGING_DISABLED = 67,
	ESIF_EVENT_DPTF_PARTICIPANT_ACTIVITY_LOGGING_ENABLED = 68,
	ESIF_EVENT_DPTF_PARTICIPANT_ACTIVITY_LOGGING_DISABLED = 69,
	ESIF_EVENT_DPTF_PARTICIPANT_CONTROL_ACTION = 70,
	ESIF_EVENT_DOMAIN_MAX_BATTERY_POWER_CHANGED = 71,
	ESIF_EVENT_OS_POWERSCHEME_PERSONALITY_CHANGED = 72,
	ESIF_EVENT_OS_MOBILE_NOTIFICATION = 73,
	ESIF_EVENT_EMERGENCY_CALL_MODE_TABLE_CHANGED = 74,
	ESIF_EVENT_APP_LOADED = 75,
	ESIF_EVENT_APP_UNLOADED = 76,
	ESIF_EVENT_ADAPTIVE_PERFORMANCE_PARTICIPANT_CONDITION_TABLE_CHANGED = 77,
	ESIF_EVENT_ACTION_LOADED = 78,
	ESIF_EVENT_ACTION_UNLOADED = 79,
	ESIF_EVENT_PID_ALGORITHM_TABLE_CHANGED = 80,
	ESIF_EVENT_POWER_BOSS_MATH_TABLE_CHANGED = 81,
	ESIF_EVENT_APP_UNLOADING = 82,
	ESIF_EVENT_ACTIVE_CONTROL_POINT_RELATIONSHIP_TABLE_CHANGED = 83,
	ESIF_EVENT_PARTICIPANT_UNREGISTER_COMPLETE = 84,
	ESIF_EVENT_SUPPORTED_POLICIES_CHANGED = 85,
	ESIF_EVENT_LF_UNLOADED = 86,
	ESIF_EVENT_DOMAIN_ENERGY_THRESHOLD_CROSSED = 91,
	ESIF_EVENT_POWER_SHARING_ALGORITHM_TABLE_CHANGED = 92,
	ESIF_EVENT_WORKLOAD_HINT_CONFIGURATION_CHANGED = 93,
	ESIF_EVENT_PRIMARY_PARTICIPANT_ARRIVED = 94,
	ESIF_EVENT_DOMAIN_FAN_CAPABILITIES_CHANGED = 95,
	ESIF_EVENT_APP_ALIVE_REQUEST = 96,
	ESIF_EVENT_OS_MIXED_REALITY_MODE_CHANGED = 97,
	ESIF_EVENT_BATTERY_COUNT_NOTIFICATION = 98,
	ESIF_EVENT_OS_SCREEN_STATE_CHANGED = 99,
	ESIF_EVENT_OS_USER_PRESENCE_CHANGED = 100,
	ESIF_EVENT_DOMAIN_BATTERY_HIGH_FREQUENCY_IMPEDANCE_CHANGED = 101,
	ESIF_EVENT_DOMAIN_BATTERY_NO_LOAD_VOLTAGE_CHANGED = 102,
	ESIF_EVENT_DOMAIN_BATTERY_STATE_OF_CHARGE_CHANGED = 103,
	ESIF_EVENT_DOMAIN_BATTERY_TEMPERATURE_CHANGED = 104,
	ESIF_EVENT_VOLTAGE_THRESHOLD_MATH_TABLE_CHANGED = 105,
	ESIF_EVENT_OS_POWER_SLIDER_VALUE_CHANGED = 106,
	ESIF_EVENT_DOMAIN_WORKLOAD_CLASSIFICATION_CHANGED = 107,
	ESIF_EVENT_POWER_SHARING_ALGORITHM_TABLE_2_CHANGED = 108,
	ESIF_EVENT_OS_GAME_MODE_CHANGED = 109,
	ESIF_EVENT_SESSION_STATE_CHANGED = 110,
	ESIF_EVENT_SENSOR_USER_PRESENCE_CHANGED = 111,
	ESIF_EVENT_ADAPTIVE_USER_PRESENCE_TABLE_CHANGED = 112,
	ESIF_EVENT_ADAPTIVE_DIMMING_FEATURE_STATE_CHANGED = 113,
	ESIF_EVENT_ADAPTIVE_DIMMING_EXTERNAL_MONITOR_FEATURE_STATE_CHANGED = 114,
	ESIF_EVENT_NO_LOCK_ON_PRESENCE_FEATURE_STATE_CHANGED = 115,
	ESIF_EVENT_WALK_AWAY_LOCK_FEATURE_STATE_CHANGED = 116,
	ESIF_EVENT_WALK_AWAY_LOCK_EXTERNAL_MONITOR_FEATURE_STATE_CHANGED = 117,
	ESIF_EVENT_WAKE_ON_APPROACH_FEATURE_STATE_CHANGED = 118,
	ESIF_EVENT_WAKE_ON_APPROACH_EXTERNAL_MONITOR_FEATURE_STATE_CHANGED = 119,
	ESIF_EVENT_SCREEN_LOCK_WAIT_TIME_CHANGED = 120,
	ESIF_EVENT_ADAPTIVE_DIMMING_PRESENTATION_MODE_FEATURE_STATE_CHANGED = 121,
	ESIF_EVENT_PLATFORM_USER_PRESENCE_CHANGED = 122,
	ESIF_EVENT_WAKE_ON_APPROACH_LOW_BATTERY_FEATURE_STATE_CHANGED = 124,
	ESIF_EVENT_WAKE_ON_APPROACH_BATTERY_REMAINING_PERCENTAGE_CHANGED = 125,
	ESIF_EVENT_WALK_AWAY_LOCK_DIM_SCREEN_FEATURE_STATE_CHANGED = 126,
	ESIF_EVENT_WALK_AWAY_LOCK_DISPLAY_OFF_AFTER_LOCK_FEATURE_STATE_CHANGED = 127,
	ESIF_EVENT_WALK_AWAY_LOCK_HONOR_DISPLAY_POWER_REQUEST_FEATURE_STATE_CHANGED = 128,
	ESIF_EVENT_WALK_AWAY_LOCK_HONOR_USER_IN_CALL_FEATURE_STATE_CHANGED = 129,
	ESIF_EVENT_NO_LOCK_ON_PRESENCE_BATTERY_FEATURE_STATE_CHANGED = 130,
	ESIF_EVENT_NO_LOCK_ON_PRESENCE_BATTERY_REMAINING_PERCENTAGE_CHANGED = 131,
	ESIF_EVENT_NO_LOCK_ON_PRESENCE_RESET_WAIT_TIME_CHANGED = 132,
	ESIF_EVENT_USER_PRESENT_WAIT_TIMEOUT_CHANGED = 134,
	ESIF_EVENT_WALK_AWAY_LOCK_PRE_DIM_WAIT_TIME_CHANGED = 135,
	ESIF_EVENT_WALK_AWAY_LOCK_DIM_INTERVAL_CHANGED = 136,
	ESIF_EVENT_CONTEXT_SERVICE_STATUS_CHANGED = 137,
	ESIF_EVENT_ADAPTIVE_DIMMING_PRE_DIM_WAIT_TIME_CHANGED = 138,
	ESIF_EVENT_EXTERNAL_MONITOR_CONNECTION_STATE_CHANGED = 139,
	ESIF_EVENT_USER_IN_CALL_STATE_CHANGED = 140,
	ESIF_EVENT_MISPREDICTION_FACE_DETECTION_STATE_CHANGED = 141,
	ESIF_EVENT_BIOMETRIC_PRESENCE_SENSOR_INSTANCE_CHANGED = 142,
	ESIF_EVENT_MISPREDICTION_TIME_WINDOW_CHANGED = 143,
	ESIF_EVENT_MISPREDICTION_1_DIM_WAIT_TIME_CHANGED = 144,
	ESIF_EVENT_MISPREDICTION_2_DIM_WAIT_TIME_CHANGED = 145,
	ESIF_EVENT_MISPREDICTION_3_DIM_WAIT_TIME_CHANGED = 146,
	ESIF_EVENT_MISPREDICTION_4_DIM_WAIT_TIME_CHANGED = 147,
	ESIF_EVENT_FAILSAFE_TIMEOUT_CHANGED = 148,
	ESIF_EVENT_NO_LOCK_ON_PRESENCE_EXTERNAL_MONITOR_FEATURE_STATE_CHANGED = 149,
	ESIF_EVENT_PARTICIPANT_CREATE_COMPLETE = 150,
	ESIF_EVENT_USER_NOT_PRESENT_DIM_TARGET_CHANGED = 151,
	ESIF_EVENT_USER_DISENGAGED_DIMMING_INTERVAL_CHANGED = 152,
	ESIF_EVENT_USER_DISENGAGED_DIM_TARGET_CHANGED = 153,
	ESIF_EVENT_USER_DISENGAGED_DIM_WAIT_TIME_CHANGED = 154,
	ESIF_EVENT_DOMAIN_EPP_SENSITIVITY_HINT_CHANGED = 155,
	ESIF_EVENT_OS_USER_INTERACTION_CHANGED = 156,
	ESIF_EVENT_PRIVACY_STATE_CHANGED = 157,
	ESIF_EVENT_FOREGROUND_BACKGROUND_RATIO_CHANGED = 158,
	ESIF_EVENT_SENSOR_MODE_CHANGED = 159,
	ESIF_EVENT_USER_PRESENCE_CORRELATION_STATUS_CHANGED = 160,
	ESIF_EVENT_SESSION_DISCONNECTED = 10000,
} esif_event_type_t;

/* Max Enum Value for Iteration purposes.
** Note that this only includes ESIF Event Types with an associated GUID and
** does not include Event Types used outside of ESIF, such as IPF-specific Events.
*/
#define MAX_ESIF_EVENT_ENUM_VALUE  ESIF_EVENT_USER_PRESENCE_CORRELATION_STATUS_CHANGED

/* Event Type String */
static ESIF_INLINE char *esif_event_type_str(esif_event_type_t type)
{
	switch (type) {
	ESIF_CASE_ENUM(ESIF_EVENT_APP_CONNECTED_STANDBY_ENTRY);
	ESIF_CASE_ENUM(ESIF_EVENT_APP_CONNECTED_STANDBY_EXIT);
	ESIF_CASE_ENUM(ESIF_EVENT_APP_ACTIVE_RELATIONSHIP_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_APP_THERMAL_RELATIONSHIP_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_APP_FOREGROUND_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_PARTICIPANT_SUSPEND);
	ESIF_CASE_ENUM(ESIF_EVENT_PARTICIPANT_RESUME);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_CORE_CAPABILITY_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_DISPLAY_CAPABILITY_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_DISPLAY_STATUS_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_PERF_CAPABILITY_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_PERF_CONTROL_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_POWER_CAPABILITY_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_POWER_THRESHOLD_CROSSED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_PRIORITY_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_TEMP_THRESHOLD_CROSSED);
	ESIF_CASE_ENUM(ESIF_EVENT_PARTICIPANT_SPEC_INFO_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_PARTICIPANT_CREATE);
	ESIF_CASE_ENUM(ESIF_EVENT_PARTICIPANT_UNREGISTER);
	ESIF_CASE_ENUM(ESIF_EVENT_PARTICIPANT_SHUTDOWN);
	ESIF_CASE_ENUM(ESIF_EVENT_ACPI);
	ESIF_CASE_ENUM(ESIF_EVENT_PASSIVE_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DISPLAY_ORIENTATION_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DEVICE_ORIENTATION_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_MOTION_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_SYSTEM_COOLING_POLICY_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_RF_PROFILE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_RF_CONNECTION_STATUS_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_LOG_VERBOSITY_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_POWER_SOURCE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_TEMP_THRESHOLD_INTERRUPT);
	ESIF_CASE_ENUM(ESIF_EVENT_DRIVER_SUSPEND);
	ESIF_CASE_ENUM(ESIF_EVENT_DRIVER_RESUME);
	ESIF_CASE_ENUM(ESIF_EVENT_ADAPTIVE_PERFORMANCE_CONDITIONS_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_ADAPTIVE_PERFORMANCE_ACTIONS_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_POWER_SOURCE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_LID_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_BATTERY_PERCENT_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_PLATFORM_TYPE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_DOCK_MODE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OEM_VARS_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_VIRTUAL_SENSOR_CALIB_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_VIRTUAL_SENSOR_POLLING_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_VIRTUAL_SENSOR_RECALC_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_BATTERY_STATUS_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_BATTERY_INFORMATION_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_PLATFORM_BATTERY_STEADY_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_PLATFORM_POWER_SOURCE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_CHARGER_TYPE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_PLATFORM_REST_OF_POWER_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_POWER_BOSS_CONDITIONS_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_POWER_BOSS_ACTIONS_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DPTF_POLICY_LOADED_UNLOADED);
	ESIF_CASE_ENUM(ESIF_EVENT_DPTF_POLICY_ACTIVITY_LOGGING_ENABLED);
	ESIF_CASE_ENUM(ESIF_EVENT_DPTF_POLICY_ACTIVITY_LOGGING_DISABLED);
	ESIF_CASE_ENUM(ESIF_EVENT_DPTF_PARTICIPANT_ACTIVITY_LOGGING_ENABLED);
	ESIF_CASE_ENUM(ESIF_EVENT_DPTF_PARTICIPANT_ACTIVITY_LOGGING_DISABLED);
	ESIF_CASE_ENUM(ESIF_EVENT_DPTF_PARTICIPANT_CONTROL_ACTION);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_MAX_BATTERY_POWER_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_POWERSCHEME_PERSONALITY_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_MOBILE_NOTIFICATION);
	ESIF_CASE_ENUM(ESIF_EVENT_EMERGENCY_CALL_MODE_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_APP_LOADED);
	ESIF_CASE_ENUM(ESIF_EVENT_APP_UNLOADED);
	ESIF_CASE_ENUM(ESIF_EVENT_ADAPTIVE_PERFORMANCE_PARTICIPANT_CONDITION_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_ACTION_LOADED);
	ESIF_CASE_ENUM(ESIF_EVENT_ACTION_UNLOADED);
	ESIF_CASE_ENUM(ESIF_EVENT_PID_ALGORITHM_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_POWER_BOSS_MATH_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_APP_UNLOADING);
	ESIF_CASE_ENUM(ESIF_EVENT_ACTIVE_CONTROL_POINT_RELATIONSHIP_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_PARTICIPANT_UNREGISTER_COMPLETE);
	ESIF_CASE_ENUM(ESIF_EVENT_SUPPORTED_POLICIES_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_LF_UNLOADED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_ENERGY_THRESHOLD_CROSSED);
	ESIF_CASE_ENUM(ESIF_EVENT_POWER_SHARING_ALGORITHM_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WORKLOAD_HINT_CONFIGURATION_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_PRIMARY_PARTICIPANT_ARRIVED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_FAN_CAPABILITIES_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_APP_ALIVE_REQUEST);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_MIXED_REALITY_MODE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_BATTERY_COUNT_NOTIFICATION);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_SCREEN_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_USER_PRESENCE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_BATTERY_HIGH_FREQUENCY_IMPEDANCE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_BATTERY_NO_LOAD_VOLTAGE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_BATTERY_STATE_OF_CHARGE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_BATTERY_TEMPERATURE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_VOLTAGE_THRESHOLD_MATH_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_POWER_SLIDER_VALUE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_WORKLOAD_CLASSIFICATION_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_POWER_SHARING_ALGORITHM_TABLE_2_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_GAME_MODE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_SESSION_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_SENSOR_USER_PRESENCE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_ADAPTIVE_USER_PRESENCE_TABLE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_ADAPTIVE_DIMMING_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_ADAPTIVE_DIMMING_EXTERNAL_MONITOR_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_NO_LOCK_ON_PRESENCE_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WALK_AWAY_LOCK_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WALK_AWAY_LOCK_EXTERNAL_MONITOR_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WAKE_ON_APPROACH_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WAKE_ON_APPROACH_EXTERNAL_MONITOR_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_SCREEN_LOCK_WAIT_TIME_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_ADAPTIVE_DIMMING_PRESENTATION_MODE_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_PLATFORM_USER_PRESENCE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WAKE_ON_APPROACH_LOW_BATTERY_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WAKE_ON_APPROACH_BATTERY_REMAINING_PERCENTAGE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WALK_AWAY_LOCK_DIM_SCREEN_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WALK_AWAY_LOCK_DISPLAY_OFF_AFTER_LOCK_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WALK_AWAY_LOCK_HONOR_DISPLAY_POWER_REQUEST_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WALK_AWAY_LOCK_HONOR_USER_IN_CALL_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_NO_LOCK_ON_PRESENCE_BATTERY_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_NO_LOCK_ON_PRESENCE_BATTERY_REMAINING_PERCENTAGE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_NO_LOCK_ON_PRESENCE_RESET_WAIT_TIME_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_USER_PRESENT_WAIT_TIMEOUT_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WALK_AWAY_LOCK_PRE_DIM_WAIT_TIME_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_WALK_AWAY_LOCK_DIM_INTERVAL_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_CONTEXT_SERVICE_STATUS_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_ADAPTIVE_DIMMING_PRE_DIM_WAIT_TIME_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_EXTERNAL_MONITOR_CONNECTION_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_USER_IN_CALL_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_MISPREDICTION_FACE_DETECTION_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_BIOMETRIC_PRESENCE_SENSOR_INSTANCE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_MISPREDICTION_TIME_WINDOW_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_MISPREDICTION_1_DIM_WAIT_TIME_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_MISPREDICTION_2_DIM_WAIT_TIME_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_MISPREDICTION_3_DIM_WAIT_TIME_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_MISPREDICTION_4_DIM_WAIT_TIME_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_FAILSAFE_TIMEOUT_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_NO_LOCK_ON_PRESENCE_EXTERNAL_MONITOR_FEATURE_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_PARTICIPANT_CREATE_COMPLETE);
	ESIF_CASE_ENUM(ESIF_EVENT_USER_NOT_PRESENT_DIM_TARGET_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_USER_DISENGAGED_DIMMING_INTERVAL_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_USER_DISENGAGED_DIM_TARGET_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_USER_DISENGAGED_DIM_WAIT_TIME_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_DOMAIN_EPP_SENSITIVITY_HINT_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_OS_USER_INTERACTION_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_PRIVACY_STATE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_FOREGROUND_BACKGROUND_RATIO_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_SENSOR_MODE_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_USER_PRESENCE_CORRELATION_STATUS_CHANGED);
	ESIF_CASE_ENUM(ESIF_EVENT_SESSION_DISCONNECTED);
	}
	return ESIF_NOT_AVAILABLE;
}
