/******************************************************************************
** Copyright (c) 2013-2020 Intel Corporation All Rights Reserved
**
** Licensed under the Apache License, Version 2.0 (the "License"); you may not
** use this file except in compliance with the License.
**
** You may obtain a copy of the License at
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
** WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
**
** See the License for the specific language governing permissions and
** limitations under the License.
**
******************************************************************************/

#include "Dptf.h"
#include "WIDomainAllocate.h"
#include "WIDomainCoreControlCapabilityChanged.h"
#include "WIDomainCreate.h"
#include "WIDomainDestroy.h"
#include "WIDomainDisplayControlCapabilityChanged.h"
#include "WIDomainDisplayStatusChanged.h"
#include "WIDomainPerformanceControlCapabilityChanged.h"
#include "WIDomainPerformanceControlsChanged.h"
#include "WIDomainPowerControlCapabilityChanged.h"
#include "WIDomainPriorityChanged.h"
#include "WIDomainRadioConnectionStatusChanged.h"
#include "WIDomainRfProfileChanged.h"
#include "WIDomainTemperatureThresholdCrossed.h"
#include "WIDomainVirtualSensorCalibrationTableChanged.h"
#include "WIDomainVirtualSensorPollingTableChanged.h"
#include "WIDomainVirtualSensorRecalcChanged.h"
#include "WIDomainBatteryStatusChanged.h"
#include "WIDomainBatteryInformationChanged.h"
#include "WIDomainBatteryHighFrequencyImpedanceChanged.h"
#include "WIDomainBatteryNoLoadVoltageChanged.h"
#include "WIDomainPlatformPowerSourceChanged.h"
#include "WIDomainAdapterPowerRatingChanged.h"
#include "WIDomainChargerTypeChanged.h"
#include "WIDomainPlatformRestOfPowerChanged.h"
#include "WIDomainMaxBatteryPowerChanged.h"
#include "WIDomainPlatformBatterySteadyStateChanged.h"
#include "WIDomainACNominalVoltageChanged.h"
#include "WIDomainACOperationalCurrentChanged.h"
#include "WIDomainAC1msPercentageOverloadChanged.h"
#include "WIDomainAC2msPercentageOverloadChanged.h"
#include "WIDomainAC10msPercentageOverloadChanged.h"
#include "WIDomainEnergyThresholdCrossed.h"
#include "WIDomainFanCapabilityChanged.h"
#include "WIDomainSocWorkloadClassificationChanged.h"
#include "WIDomainEppSensitivityHintChanged.h"
#include "WIDptfConnectedStandbyEntry.h"
#include "WIDptfConnectedStandbyExit.h"
#include "WIDptfResume.h"
#include "WIDptfSuspend.h"
#include "WIDptfGetStatus.h"
#include "WIDptfParticipantActivityLoggingEnabled.h"
#include "WIDptfParticipantActivityLoggingDisabled.h"
#include "WIParticipantAllocate.h"
#include "WIParticipantCreate.h"
#include "WIParticipantDestroy.h"
#include "WIParticipantSpecificInfoChanged.h"
#include "WIPolicyActiveRelationshipTableChanged.h"
#include "WIPolicyCoolingModePolicyChanged.h"
#include "WIPolicyCreateAll.h"
#include "WIPolicyDestroy.h"
#include "WIPolicyForegroundApplicationChanged.h"
#include "WIPolicyInitiatedCallback.h"
#include "WIPolicyOperatingSystemPowerSourceChanged.h"
#include "WIPolicyOperatingSystemLidStateChanged.h"
#include "WIPolicyOperatingSystemBatteryPercentageChanged.h"
#include "WIPolicyOperatingSystemPlatformTypeChanged.h"
#include "WIPolicyOperatingSystemDockModeChanged.h"
#include "WIPolicyOperatingSystemMobileNotification.h"
#include "WIPolicyOperatingSystemMixedRealityModeChanged.h"
#include "WIPolicyOperatingSystemPowerSchemePersonalityChanged.h"
#include "WIPolicyOperatingSystemUserPresenceChanged.h"
#include "WIPolicyOperatingSystemSessionStateChanged.h"
#include "WIPolicyOperatingSystemScreenStateChanged.h"
#include "WIPolicyOperatingSystemBatteryCountChanged.h"
#include "WIPolicyOperatingSystemPowerSliderChanged.h"
#include "WIPolicyPassiveTableChanged.h"
#include "WIPolicySensorOrientationChanged.h"
#include "WIPolicySensorMotionChanged.h"
#include "WIPolicySensorSpatialOrientationChanged.h"
#include "WIPolicySupportedListChanged.h"
#include "WIPolicyThermalRelationshipTableChanged.h"
#include "WIPolicyAdaptivePerformanceConditionsTableChanged.h"
#include "WIPolicyAdaptivePerformanceParticipantConditionTableChanged.h"
#include "WIPolicyAdaptivePerformanceActionsTableChanged.h"
#include "WIPolicyOemVariablesChanged.h"
#include "WIPolicyPowerBossConditionsTableChanged.h"
#include "WIPolicyPowerBossActionsTableChanged.h"
#include "WIPolicyPowerBossMathTableChanged.h"
#include "WIPolicyVoltageThresholdMathTableChanged.h"
#include "WIDptfPolicyActivityLoggingEnabled.h"
#include "WIDptfPolicyActivityLoggingDisabled.h"
#include "WIPolicyEmergencyCallModeTableChanged.h"
#include "WIPolicyPidAlgorithmTableChanged.h"
#include "WIPolicyActiveControlPointRelationshipTableChanged.h"
#include "WIPolicyPowerShareAlgorithmTableChanged.h"
#include "WIPowerLimitChanged.h"
#include "WIPerformanceCapabilitiesChanged.h"
#include "WIPolicyWorkloadHintConfigurationChanged.h"
#include "WIApplicationAliveRequest.h"
#include "WIPolicyOperatingSystemGameModeChanged.h"
#include "WIPolicyPowerShareAlgorithmTable2Changed.h"
#include "WIPolicySensorUserPresenceChanged.h"
#include "WIPolicyAdaptiveUserPresenceTableChanged.h"
#include "WIPolicyPlatformUserPresenceChanged.h"
#include "WIPolicyAdaptiveDimmingFeatureStateChanged.h"
#include "WIPolicyAdaptiveDimmingWithExternalMonitorFeatureStateChanged.h"
#include "WIPolicyAdaptiveDimmingWithPresentationModeFeatureStateChanged.h"
#include "WIPolicyAdaptiveDimmingPreDimWaitTimeChanged.h"
#include "WIPolicyMispredictionFaceDetectionFeatureStateChanged.h"
#include "WIPolicyMispredictionTimeWindowChanged.h"
#include "WIPolicyMisprediction1DimWaitTimeChanged.h"
#include "WIPolicyMisprediction2DimWaitTimeChanged.h"
#include "WIPolicyMisprediction3DimWaitTimeChanged.h"
#include "WIPolicyMisprediction4DimWaitTimeChanged.h"
#include "WIPolicyNoLockOnPresenceBatteryRemainingPercentageChanged.h"
#include "WIPolicyNoLockOnPresenceFeatureStateChanged.h"
#include "WIPolicyNoLockOnPresenceExternalMonitorFeatureStateChanged.h"
#include "WIPolicyNoLockOnPresenceOnBatteryFeatureStateChanged.h"
#include "WIPolicyNoLockOnPresenceResetWaitTimeChanged.h"
#include "WIPolicyFailsafeTimeoutChanged.h"
#include "WIPolicyWakeOnApproachFeatureStateChanged.h"
#include "WIPolicyWakeOnApproachBatteryRemainingPercentageChanged.h"
#include "WIPolicyWakeOnApproachOnLowBatteryFeatureStateChanged.h"
#include "WIPolicyWakeOnApproachWithExternalMonitorFeatureStateChanged.h"
#include "WIPolicyWalkAwayLockDimScreenFeatureStateChanged.h"
#include "WIPolicyWalkAwayLockDisplayOffAfterLockFeatureStateChanged.h"
#include "WIPolicyWalkAwayLockFeatureStateChanged.h"
#include "WIPolicyWalkAwayLockUserPresentWaitTimeChanged.h"
#include "WIPolicyWalkAwayLockDimIntervalChanged.h"
#include "WIPolicyWalkAwayLockPreDimWaitTimeChanged.h"
#include "WIPolicyWalkAwayLockHonorPowerRequestsForDisplayFeatureStateChanged.h"
#include "WIPolicyWalkAwayLockHonorUserInCallFeatureStateChanged.h"
#include "WIPolicyUserInCallStateChanged.h"
#include "WIPolicyWalkAwayLockScreenLockWaitTimeChanged.h"
#include "WIPolicyWalkAwayLockWithExternalMonitorFeatureStateChanged.h"
#include "WIPolicyContextServiceStatusChanged.h"
#include "WIPolicyExternalMonitorStateChanged.h"
#include "WIPolicyUserNotPresentDimTargetChanged.h"
#include "WIPolicyUserDisengagedDimmingIntervalChanged.h"
#include "WIPolicyUserDisengagedDimTargetChanged.h"
#include "WIPolicyUserDisengagedDimWaitTimeChanged.h"
#include "WIPolicySensorModeChanged.h"
#include "WIPolicyBiometricPresenceSensorInstanceChanged.h"
#include "WIPolicyUserInteractionChanged.h"
#include "WIPolicyUserPresenceCorrelationStatusChanged.h"
#include "WIPolicyForegroundRatioChanged.h"
